// @ts-nocheck — node build script, not app code (svelte-check picks up .mjs files)
// Cache-buster for /assets/* — production serves them with Cache-Control: immutable, so a URL must
// change whenever its content changes or browsers keep year-old files forever (the "old atlas under
// new frame coordinates" bug). Runs before every `pnpm dev` / `pnpm build`:
//   1. bakes hashes INSIDE the loader JSONs (atlas meta.pngHash, audiosprite src[] ?v=),
//   2. hashes every file under static/assets and writes src/game/assetStamp.ts, which assets.ts
//      uses to append ?v=<hash> to the top-level URLs.
// Pixi's checkExtension and Howler's format sniffing both strip ?query — verified safe.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = dirname(dirname(fileURLToPath(import.meta.url)));
const ASSETS = join(APP, 'static', 'assets');

const h8 = (path) => createHash('md5').update(readFileSync(path)).digest('hex').slice(0, 8);
const strip = (ref) => ref.split('?')[0];

// 1a. sprite atlases: Pixi's spritesheet loader copies the JSON URL's search params onto the
// meta.image request (copySearchParams), so the PNG is fetched as <name>.png?v=<stamp of the JSON>.
// Embedding the PNG's own hash as a custom meta field makes the JSON's bytes — and therefore both
// URLs — change whenever the PNG changes, even if the frame coordinates didn't.
for (const name of ['amSymbols', 'amCharacters']) {
	const jsonPath = join(ASSETS, 'sprites', name, `${name}.json`);
	const meta = JSON.parse(readFileSync(jsonPath, 'utf8'));
	const png = strip(meta.meta.image);
	meta.meta.image = png; // plain — the stamp arrives via copySearchParams from the JSON URL
	meta.meta.pngHash = h8(join(dirname(jsonPath), png));
	writeFileSync(jsonPath, JSON.stringify(meta, null, 1) + '\n');
}

// 1b. audiosprite: src[] entries -> "./assets/audio/sounds.<ext>?v=<hash of that file>"
{
	const jsonPath = join(ASSETS, 'audio', 'sounds.json');
	const manifest = JSON.parse(readFileSync(jsonPath, 'utf8'));
	manifest.src = manifest.src.map((ref) => {
		const clean = strip(ref);
		return `${clean}?v=${h8(join(ASSETS, 'audio', clean.split('/').pop()))}`;
	});
	writeFileSync(jsonPath, JSON.stringify(manifest, null, '\t') + '\n');
}

// 2. hash everything under static/assets (after the rewrites above, so JSON stamps reflect final bytes)
const stamps = {};
const walk = (dir) => {
	for (const entry of readdirSync(dir).sort()) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) walk(full);
		else if (!/^\.|\.py$/.test(entry)) stamps[relative(ASSETS, full)] = h8(full);
	}
};
walk(ASSETS);

const out = `// AUTO-GENERATED by scripts/stamp-assets.mjs — do not edit; regenerated on every dev/build.
// Content hashes for files under static/assets, keyed by path relative to static/assets.
export default ${JSON.stringify(stamps, null, '\t')} as const;
`;
writeFileSync(join(APP, 'src', 'game', 'assetStamp.ts'), out);
console.log(`stamp-assets: ${Object.keys(stamps).length} files stamped`);
