#!/usr/bin/env python
"""Game assets for the courtyard scene (components/Background.svelte, game/scene.ts): the painted backdrops, the 3D
foreground, the brazier fire pass and the moving knocker rings and chains, for the landscape and phone sideways layouts.

  /Users/corey/Projects/stake-engine/math-sdk/env/bin/python tools/build_scene_assets.py [SRC] [--portrait DIR] [--backdrops DIR] [--fallback DIR]
  node scripts/stamp-assets.mjs          (afterwards, from the app folder)

SRC alone rebuilds the landscape set, --portrait DIR alone the portrait set, both together everything. The side a run
does not rebuild keeps its files and its block of sceneSpec.ts.

SRC (read only, never written) is one of the scene agent's deliverable folders, for example
~/Desktop/Manticore Mayhem/images/backgrounds/base/drafts/scene_blockout/lookdev/knocker :
  day_base_2560.png, night_base_2560.png   the foreground with alpha, no brazier light, no moving chains
  fire_pass_2560.png (or fire_pass_1280)   the brazier light alone, with alpha, to be ADDED over the base
  sprites/*_<piece>_<side>_<set>*.png      piece ring / hang / swag, side L / R, set day / night: 12 files (or wherever
                                           the json's file_day / file_night say, relative to SRC)
  chain_layers.json                        every sprite's box, the pivots and hook points (px of the frame), the
                                           draw order. EVERY number the game uses comes from this file: nothing is
                                           hard-coded here and the right side is never assumed to mirror the left.
--backdrops (default .../drafts/backdrop_upscale): backdropv2_2560_digital-art-4x.png (day) and
backdrop_night_2560_digital-art-4x.png (night), opaque, behind the foreground.
--fallback: a folder to take a base or the fire pass from when SRC does not have its own (a round that only re-rendered
the chains). Default: the one other folder chain_layers.json takes sprites from (its file_day / file_night paths), if
there is one. Printed when used.

Outputs, everything regenerated by one run, two tiers (game/deviceTier.ts): full = the frame's own size, phone = 1600 wide:
  static/assets/backgrounds/scene/backdrop-<day|night>[-phone].webp   opaque
  static/assets/backgrounds/scene/fore-<day|night>[-phone].webp       with alpha
  static/assets/backgrounds/scene/fire[-phone].webp                   the pass ON BLACK, opaque, half the base's size:
                                                                      the game draws it with the additive blend
  static/assets/backgrounds/scene/chains[-phone].json|webp            ONE atlas, both sets: scene_<piece>_<side>_<set>
  src/game/sceneSpec.ts                                               the frame, the tiers, the points and each
                                                                      sprite's box per tier, in px of the frame

--portrait DIR (read only), for example .../lookdev/portrait_r2 : portrait_layers.json names the files (backdrop_day,
backdrop_night, base_day, base_night, fire_pass_full or fire_pass) and the 9:16 frame. No moving pieces. Outputs, full =
the frame's own size (1440 x 2560), phone = 900 wide:
  static/assets/backgrounds/scene/portrait-backdrop-<day|night>[-phone].webp
  static/assets/backgrounds/scene/portrait-fore-<day|night>[-phone].webp
  static/assets/backgrounds/scene/portrait-fire[-phone].webp          on black, half the base's size
  src/game/sceneSpec.ts SCENE_SPEC_PORTRAIT                           the frame, the tiers, the painting's and the fill's rows

CHECKS printed: every file's size and its GPU memory (w x h x 4); the backdrops' banding check against the
source (flat pixels in the smooth parts, see band_check: asserted under BAND_TOLERANCE; printed only for the fire pass);
the sprites laid back over the frame against the source sprites.
"""
from __future__ import annotations

import argparse
import glob
import hashlib
import json
import os
import sys

import numpy as np
from PIL import Image

APP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(APP, 'static', 'assets', 'backgrounds', 'scene')
SPEC = os.path.join(APP, 'src', 'game', 'sceneSpec.ts')
DRAFTS = os.path.expanduser('~/Desktop/Manticore Mayhem/images/backgrounds/base/drafts')

# the tiers: the texture width of the base (the frame's own width on the full tier). The fire pass ships at FIRE_SHARE
# of the base's size in both (the scene agent's half size test: mean difference 1.2 of 255 at the EPIC level).
PHONE_WIDTH = 1600
PORTRAIT_PHONE_WIDTH = 900
FIRE_SHARE = 0.5
# webp qualities. The backdrop is the one with a sky gradient: checked below, raise it if the check ever fails.
Q_BACKDROP = 90
Q_FORE = 88
Q_FIRE = 92
Q_SPRITES = 92
# the banding check (band_check below): how many more flat pixels, as a share of the smooth parts, a backdrop or the
# fire pass may have than its source
BAND_TOLERANCE = 0.10
BAND_BOX = 9
BAND_SMOOTH = 2.5
# transparent texels kept round every sprite in the atlas (it is drawn rotated, with linear sampling), and between frames
SPRITE_MARGIN = 1
ATLAS_PAD = 2

PIECES = ('ring', 'hang', 'swag')
SIDES = ('L', 'R')
SETS = ('day', 'night')
# our name -> the names chain_layers.json has used for it (knocker, knocker_r2)
POINTS = {
    'pivot': ('mouth_pivot',),
    'hangHook': ('hang_hook_ring_bottom', 'hang_attach_ring_bottom'),
    'hangEnd': ('hang_free_end_lowest_pixel', 'hang_bottom'),
    'swagHook': ('swag_hook_on_ring', 'swag_attach_on_ring'),
    'swagEnd': ('swag_disappears_behind_bowl',),
}
# the swag's PIN is where it goes behind the bowl rim. A deep swag shows again under the bowl (knocker_r2, right), and
# then the json's lowest visible point is that lower piece, not the rim crossing. So the pin is read from the sprite:
# the last row of its first unbroken run of rows from the top (alpha over PIN_ALPHA, a break is PIN_GAP empty rows).
PIN_ALPHA = 128
PIN_GAP = 3


def die(msg: str):
    sys.exit(f'build_scene_assets: {msg}')


def find(src: str, fallback: str | None, *names: str) -> str:
    for folder in (src, fallback):
        if not folder:
            continue
        for name in names:
            path = os.path.join(folder, name)
            if os.path.isfile(path):
                if folder != src:
                    print(f'  NOTE {names[0]}: not in the source folder, taken from {path}')
                return path
    die(f'{" / ".join(names)} not found in {src}' + (f' or {fallback}' if fallback else ''))


def resize_rgba(im: Image.Image, size: tuple[int, int], box=None) -> Image.Image:
    """premultiplied, so a transparent texel's colour never bleeds into an edge"""
    if im.size == size and box is None:
        return im
    return im.convert('RGBa').resize(size, Image.LANCZOS, box=box).convert('RGBA')


def save_webp(im: Image.Image, name: str, quality: int, **kw) -> int:
    path = os.path.join(OUT, name)
    im.save(path, 'WEBP', quality=quality, method=6, **kw)
    return os.path.getsize(path)


def box_mean(a: np.ndarray, n: int) -> np.ndarray:
    """n x n box mean of a (h, w, c) array through an integral image"""
    pad = np.pad(a, ((1, 0), (1, 0), (0, 0)))
    s = pad.cumsum(0).cumsum(1)
    return (s[n:, n:] - s[:-n, n:] - s[n:, :-n] + s[:-n, :-n]) / (n * n)


def band_check(name: str, source: Image.Image) -> tuple[float, float, float]:
    """a banded gradient is a gradient turned into flat steps. In the SMOOTH parts of the source (9 x 9 deviation under
    BAND_SMOOTH levels and not black: the sky, the glow on the floor) count the pixels whose luma equals both its right
    and lower neighbour, in the source and in the shipped file. Returns the two shares and the mean abs error."""
    got = np.asarray(Image.open(os.path.join(OUT, name)).convert('RGB')).astype(np.float64)
    want = np.asarray(source.convert('RGB')).astype(np.float64)
    m, m2 = box_mean(want, BAND_BOX), box_mean(want * want, BAND_BOX)
    smooth = (np.sqrt(np.maximum(m2 - m * m, 0)).max(2) < BAND_SMOOTH) & (m.max(2) > 4)
    k = BAND_BOX // 2

    def flat(a: np.ndarray) -> float:
        y = (a @ [0.299, 0.587, 0.114]).round()
        f = (y[:-1, :-1] == y[1:, :-1]) & (y[:-1, :-1] == y[:-1, 1:])
        return float(f[k:k + smooth.shape[0], k:k + smooth.shape[1]][smooth].mean())

    return flat(want), flat(got), float(np.abs(got - want).mean())


def report_band(name: str, source: Image.Image, knob: str | None):
    a, b, mean = band_check(name, source)
    print(f'  {name}: flat pixels in the smooth parts {a * 100:.1f}% in the source, {b * 100:.1f}% shipped '
          + (f'(tolerance +{BAND_TOLERANCE * 100:.0f} points)' if knob else '(printed only)') + f', mean abs error {mean:.2f} of 255')
    if knob and b - a > BAND_TOLERANCE:
        die(f'{name} bands: raise {knob}')


def skyline_pack(sizes: list[tuple[int, int]], width: int) -> tuple[list[tuple[int, int]], int]:
    """bottom-left skyline: each rect at the lowest place it fits, tallest first. Returns positions and the height."""
    sky = [0] * width
    pos: list[tuple[int, int] | None] = [None] * len(sizes)
    for i in sorted(range(len(sizes)), key=lambda k: (-sizes[k][1], -sizes[k][0])):
        w, h = sizes[i]
        best = None
        for x in range(0, width - w + 1):
            y = max(sky[x:x + w])
            if best is None or y < best[1]:
                best = (x, y)
        if best is None:
            return [], 1 << 30
        x, y = best
        for k in range(x, x + w):
            sky[k] = y + h
        pos[i] = (x, y)
    return pos, max(sky)  # type: ignore[return-value]


def build_landscape(args) -> tuple[dict, list]:
    """the landscape / phone sideways scene from SRC: the 14 files, and the spec block"""
    src = os.path.abspath(os.path.expanduser(args.src))
    fallback = os.path.abspath(os.path.expanduser(args.fallback)) if args.fallback else None

    layers_path = os.path.join(src, 'chain_layers.json')
    if not os.path.isfile(layers_path):
        die(f'no chain_layers.json in {src}')
    layers = json.load(open(layers_path))
    FW, FH = layers['frame']
    tiers = {'full': FW, 'phone': PHONE_WIDTH}
    print(f'source {src}\nframe {FW} x {FH}')

    # ---- the draw order of the moving pieces, as the scene agent lists it ------------------------------------------
    order = []
    for entry in layers['draw_order']:
        for piece in PIECES:
            if piece in entry.lower() and 'sprite' in entry.lower():
                order.append(piece)
    if sorted(order) != sorted(PIECES):
        die(f'draw_order does not name the three sprites once each: {layers["draw_order"]}')
    lower = [e.lower() for e in layers['draw_order']]
    first_sprite = min(i for i, e in enumerate(lower) if 'sprite' in e)
    if not (any('base' in e for e in lower[:first_sprite]) and any('fire' in e for e in lower[:first_sprite])):
        die(f'draw_order: the base and the fire pass must come before the sprites: {layers["draw_order"]}')

    # ---- the points and boxes, both sides read explicitly ----------------------------------------------------------
    points = {}
    boxes = {}
    for side in SIDES:
        pts = layers.get(f'points_{side}')
        if not pts:
            die(f'chain_layers.json has no points_{side}')
        points[side] = {}
        for ours, theirs in POINTS.items():
            name = next((t for t in theirs if t in pts), None)
            if name is None:
                die(f'points_{side} has none of {" / ".join(theirs)}')
            points[side][ours] = [float(pts[name][0]), float(pts[name][1])]
        for piece in PIECES:
            entry = layers.get(f'{piece}_{side}')
            if not entry or 'box_x0y0x1y1' not in entry:
                die(f'chain_layers.json has no {piece}_{side}.box_x0y0x1y1')
            boxes[f'{piece}_{side}'] = [int(v) for v in entry['box_x0y0x1y1']]

    # ---- the sprites -----------------------------------------------------------------------------------------------
    sprites: dict[str, Image.Image] = {}
    shared: set[str] = set()  # folders the json takes sprites from besides SRC
    for piece in PIECES:
        for side in SIDES:
            x0, y0, x1, y1 = boxes[f'{piece}_{side}']
            for st in SETS:
                # the json names the file when a round reuses sprites from another folder; otherwise by name
                named = layers[f'{piece}_{side}'].get(f'file_{st}')
                if named:
                    hits = [os.path.normpath(os.path.join(src, named))]
                    if not os.path.isfile(hits[0]):
                        die(f'{piece}_{side}.file_{st}: {hits[0]} does not exist')
                    if not hits[0].startswith(src + os.sep):
                        shared.add(os.path.dirname(os.path.dirname(hits[0])))
                else:
                    hits = sorted(glob.glob(os.path.join(src, 'sprites', f'*{piece}_{side}_{st}*.png')))
                    if len(hits) != 1:
                        die(f'sprites/*{piece}_{side}_{st}*.png: {len(hits)} files, wanted exactly one')
                im = Image.open(hits[0]).convert('RGBA')
                if im.size != (x1 - x0, y1 - y0):
                    die(f'{os.path.basename(hits[0])} is {im.size}, its box in chain_layers.json is {(x1 - x0, y1 - y0)}')
                sprites[f'{piece}_{side}_{st}'] = im

    # ---- the swag pins, from the day sprites (see PIN_ALPHA) -------------------------------------------------------
    for side in SIDES:
        x0, y0, _, _ = boxes[f'swag_{side}']
        alpha = np.asarray(sprites[f'swag_{side}_day'])[..., 3] > PIN_ALPHA
        rows = np.nonzero(alpha.any(1))[0]
        last = rows[0]
        for r in rows[1:]:
            if r - last > PIN_GAP:
                break
            last = r
        xs = np.nonzero(alpha[last])[0]
        points[side]['swagPin'] = [round(float(x0 + xs.mean()), 1), float(y0 + last)]
        below = int((rows > last).sum())
        print(f'  swag {side}: pinned at {points[side]["swagPin"]} (the json\'s lowest visible point {points[side]["swagEnd"]}'
              + (f', {below} rows show again under the pin and stay still)' if below else ')'))

    # ---- the big layers --------------------------------------------------------------------------------------------
    # a round that re-rendered only the chains keeps its bases and fire pass in the folder its json reuses sprites from
    if not fallback and len(shared) == 1:
        fallback = shared.pop()
    fore = {st: Image.open(find(src, fallback, f'{st}_base_{FW}.png')).convert('RGBA') for st in SETS}
    for st, im in fore.items():
        if im.size != (FW, FH):
            die(f'{st} base is {im.size}, the frame is {(FW, FH)}')
    fire_src = Image.open(find(src, fallback, f'fire_pass_{FW}.png', f'fire_pass_{FW // 2}.png')).convert('RGBA')
    # on black: the additive blend adds exactly rgb x alpha, which is what the scene agent's composites add
    fire_black = Image.new('RGBA', fire_src.size, (0, 0, 0, 255))
    fire_black.alpha_composite(fire_src)
    fire_black = fire_black.convert('RGB')
    back_names = {'day': 'backdropv2_2560_digital-art-4x.png', 'night': 'backdrop_night_2560_digital-art-4x.png'}
    back = {st: Image.open(find(os.path.expanduser(args.backdrops), None, name)).convert('RGB') for st, name in back_names.items()}

    spec = {
        'source': os.path.basename(src),
        'frame': [FW, FH],
        'order': order,
        'points': points,
        'tiers': {},
    }
    report: list[tuple[str, int, int, int]] = []  # name, bytes, w, h

    for tier, width in tiers.items():
        s = width / FW
        size = (width, round(FH * s))
        fire_size = (round(size[0] * FIRE_SHARE), round(size[1] * FIRE_SHARE))
        suffix = '' if tier == 'full' else f'-{tier}'
        for st in SETS:
            # the painting is a pixel taller than the frame: fitted to it, as in the scene agent's composites
            b = back[st].resize(size, Image.LANCZOS)
            name = f'backdrop-{st}{suffix}.webp'
            report.append((name, save_webp(b, name, Q_BACKDROP), *size))
            report_band(name, b, 'Q_BACKDROP')
            f = resize_rgba(fore[st], size)
            name = f'fore-{st}{suffix}.webp'
            report.append((name, save_webp(f, name, Q_FORE, alpha_quality=100), *size))
        fp = fire_black.resize(fire_size, Image.LANCZOS)
        name = f'fire{suffix}.webp'
        report.append((name, save_webp(fp, name, Q_FIRE), *fire_size))
        # printed only: the pass is dim render noise over black, which the encoder smooths (looked at 4x gain, 2026-10-10:
        # no steps at quality 90); the count says nothing about steps there
        report_band(name, fp, None)

        # the sprites on this tier's texel grid: the box grown to whole texels plus the margin, mapped back to the frame
        tier_boxes = {}
        cells: dict[str, Image.Image] = {}
        for key, (x0, y0, x1, y1) in boxes.items():
            t0x, t0y = int(np.floor(x0 * s)) - SPRITE_MARGIN, int(np.floor(y0 * s)) - SPRITE_MARGIN
            t1x, t1y = int(np.ceil(x1 * s)) + SPRITE_MARGIN, int(np.ceil(y1 * s)) + SPRITE_MARGIN
            tier_boxes[key] = [round(v / s, 4) for v in (t0x, t0y, t1x, t1y)]
            ox, oy = int(np.floor(t0x / s)) - 4, int(np.floor(t0y / s)) - 4
            cw, ch = int(np.ceil(t1x / s)) + 4 - ox, int(np.ceil(t1y / s)) + 4 - oy
            for st in SETS:
                canvas = Image.new('RGBA', (cw, ch), (0, 0, 0, 0))
                canvas.paste(sprites[f'{key}_{st}'], (x0 - ox, y0 - oy))
                src_box = (t0x / s - ox, t0y / s - oy, t1x / s - ox, t1y / s - oy)
                if s == 1:
                    cells[f'{key}_{st}'] = canvas.crop(tuple(int(v) for v in src_box))
                else:
                    cells[f'{key}_{st}'] = resize_rgba(canvas, (t1x - t0x, t1y - t0y), box=src_box)
        names = sorted(cells)
        padded = [(cells[n].size[0] + ATLAS_PAD, cells[n].size[1] + ATLAS_PAD) for n in names]
        best = None
        for aw in range(max(w for w, _ in padded), sum(w for w, _ in padded) + 1, 4):
            pos, ah = skyline_pack(padded, aw)
            if pos and (best is None or aw * ah < best[0]):
                best = (aw * ah, aw, ah, pos)
        _, aw, ah, pos = best
        atlas = Image.new('RGBA', (aw, ah), (0, 0, 0, 0))
        frames = {}
        for n, (px, py) in zip(names, pos):
            atlas.paste(cells[n], (px, py))
            w, h = cells[n].size
            frames[f'scene_{n}'] = {'frame': {'x': px, 'y': py, 'w': w, 'h': h}, 'rotated': False, 'trimmed': False,
                                    'spriteSourceSize': {'x': 0, 'y': 0, 'w': w, 'h': h}, 'sourceSize': {'w': w, 'h': h}}
        image = f'chains{suffix}.webp'
        nbytes = save_webp(atlas, image, Q_SPRITES, alpha_quality=100)
        meta = {'image': image, 'format': 'RGBA8888', 'size': {'w': aw, 'h': ah}, 'scale': '1',
                'pngHash': hashlib.md5(open(os.path.join(OUT, image), 'rb').read()).hexdigest()[:8]}
        jpath = os.path.join(OUT, f'chains{suffix}.json')
        open(jpath, 'w').write(json.dumps({'frames': frames, 'meta': meta}, indent=1) + '\n')
        report.append((f'chains{suffix}.json + .webp', nbytes + os.path.getsize(jpath), aw, ah))

        # the check: the shipped cells laid back over the frame against the source sprites (alpha weighted colour)
        got_atlas = Image.open(os.path.join(OUT, image)).convert('RGBA')
        worst = 0.0
        for n, (px, py) in zip(names, pos):
            key, st = n.rsplit('_', 1)
            x0, y0, x1, y1 = boxes[key]
            w, h = cells[n].size
            cell = got_atlas.crop((px, py, px + w, py + h))
            b = tier_boxes[key]
            # back onto the source sprite's own pixels: its box inside the cell, in this tier's texels
            back_at = cell.convert('RGBa').resize((x1 - x0, y1 - y0), Image.BILINEAR, box=((x0 - b[0]) * s, (y0 - b[1]) * s, (x1 - b[0]) * s, (y1 - b[1]) * s))
            want = sprites[n]
            d = np.abs(np.asarray(back_at).astype(float) - np.asarray(want.convert('RGBa')).astype(float)).mean()
            worst = max(worst, d)
        print(f'  chains{suffix}: atlas {aw} x {ah}, {len(names)} frames, laid back over the frame the worst sprite differs by a mean of {worst:.2f} of 255')
        spec['tiers'][tier] = {'size': list(size), 'fire': list(fire_size), 'boxes': tier_boxes}

    return spec, report


def build_portrait(folder: str) -> tuple[dict, list]:
    """the PORTRAIT scene from its own folder (portrait_layers.json names the files): backdrop, foreground and fire pass
    only, there are no moving pieces. Same tiers rule (full = the frame, phone = PORTRAIT_PHONE_WIDTH wide), same
    qualities, same checks."""
    folder = os.path.abspath(os.path.expanduser(folder))
    layers_path = os.path.join(folder, 'portrait_layers.json')
    if not os.path.isfile(layers_path):
        die(f'no portrait_layers.json in {folder}')
    layers = json.load(open(layers_path))
    FW, FH = layers['frame']
    files = layers['files']
    print(f'portrait source {folder}\nframe {FW} x {FH}')

    def named(key: str, *alt: str) -> str:
        for k in (key, *alt):
            if k in files and os.path.isfile(os.path.join(folder, files[k])):
                return os.path.join(folder, files[k])
        die(f'portrait_layers.json files.{key}: not named or not found in {folder}')

    back = {st: Image.open(named(f'backdrop_{st}')).convert('RGB') for st in SETS}
    fore = {st: Image.open(named(f'base_{st}')).convert('RGBA') for st in SETS}
    for st in SETS:
        if back[st].size != (FW, FH) or fore[st].size != (FW, FH):
            die(f'portrait {st}: backdrop {back[st].size}, base {fore[st].size}, the frame is {(FW, FH)}')
    # the full size pass when there is one (both tiers are cut from it), else the half size one
    fire_src = Image.open(named('fire_pass_full', 'fire_pass')).convert('RGBA')
    fire_black = Image.new('RGBA', fire_src.size, (0, 0, 0, 255))
    fire_black.alpha_composite(fire_src)
    fire_black = fire_black.convert('RGB')
    # where the solid 3D begins: the first row the foreground covers (more than half, across the frame)
    cover = np.asarray(fore['day'])[..., 3].mean(1) / 255
    solid = int(np.argmax(cover > 0.5))
    notes = layers.get('backdrop_notes', {})
    for key in ('sky_extended_above_row', 'fill_below_row'):
        if key not in notes:
            die(f'portrait_layers.json backdrop_notes has no {key}')
    spec = {
        'source': os.path.basename(folder),
        'frame': [FW, FH],
        # rows of the frame: the painting, and the soft mist fill between it and the terrace's far edge (the board
        # is meant to cover the fill: tools/manticore/scene_probe.js checks that on every portrait screen)
        'painting': [int(notes['sky_extended_above_row']), int(notes['fill_below_row'])],
        'fill': [int(notes['fill_below_row']), solid],
        'tiers': {},
    }
    print(f'  the mist fill: rows {spec["fill"][0]} to {spec["fill"][1]} (the foreground covers the frame from row {solid})')
    report: list[tuple[str, int, int, int]] = []
    for tier, width in {'full': FW, 'phone': PORTRAIT_PHONE_WIDTH}.items():
        s = width / FW
        size = (width, round(FH * s))
        fire_size = (round(size[0] * FIRE_SHARE), round(size[1] * FIRE_SHARE))
        suffix = '' if tier == 'full' else f'-{tier}'
        for st in SETS:
            b = back[st].resize(size, Image.LANCZOS)
            name = f'portrait-backdrop-{st}{suffix}.webp'
            report.append((name, save_webp(b, name, Q_BACKDROP), *size))
            report_band(name, b, 'Q_BACKDROP')
            name = f'portrait-fore-{st}{suffix}.webp'
            report.append((name, save_webp(resize_rgba(fore[st], size), name, Q_FORE, alpha_quality=100), *size))
        fp = fire_black.resize(fire_size, Image.LANCZOS)
        name = f'portrait-fire{suffix}.webp'
        report.append((name, save_webp(fp, name, Q_FIRE), *fire_size))
        report_band(name, fp, None)
        spec['tiers'][tier] = {'size': list(size), 'fire': list(fire_size)}
    return spec, report


def read_spec(name: str) -> dict | None:
    """a block of the sceneSpec.ts already on disk (the side this run does not rebuild is kept as it is)"""
    if not os.path.isfile(SPEC):
        return None
    text = open(SPEC).read()
    mark = f'export const {name} = '
    if mark not in text:
        return None
    body = text[text.index(mark) + len(mark):]
    return json.loads(body[:body.index(' as const;')])


def totals(report: list, what: str):
    print('\nfile'.ljust(42) + 'KiB'.rjust(9) + '   texture'.ljust(16) + 'GPU MB (w x h x 4)')
    for name, nbytes, w, h in report:
        print(f'{name.ljust(41)}{nbytes / 1024:9.1f}   {f"{w} x {h}".ljust(13)}{w * h * 4 / 1e6:8.2f}')
    for tier in ('full', 'phone'):
        mine = [r for r in report if ('-phone' in r[0]) == (tier == 'phone')]
        first = [r for r in mine if 'night' not in r[0]]
        later = [r for r in mine if 'night' in r[0]]
        print(f'{what} {tier}: first load ({"day backdrop, day foreground, fire, the atlas" if what == "landscape" else "day backdrop, day foreground, fire"}) {sum(r[1] for r in first) / 1024:.0f} KiB, '
              f'{sum(r[2] * r[3] * 4 for r in first) / 1e6:.1f} MB on the GPU; deferred (night backdrop, night foreground) '
              f'{sum(r[1] for r in later) / 1024:.0f} KiB, {sum(r[2] * r[3] * 4 for r in later) / 1e6:.1f} MB')


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('src', nargs='?', help='the landscape scene folder (chain_layers.json, the bases, the fire pass, sprites/)')
    ap.add_argument('--portrait', default=None, help='the portrait scene folder (portrait_layers.json and the files it names)')
    ap.add_argument('--backdrops', default=os.path.join(DRAFTS, 'backdrop_upscale'))
    ap.add_argument('--fallback', default=None, help='take a base or the fire pass from here when SRC has none')
    args = ap.parse_args()
    if not args.src and not args.portrait:
        die('nothing to build: give the landscape folder, --portrait DIR, or both')
    os.makedirs(OUT, exist_ok=True)

    wide, tall = read_spec('SCENE_SPEC'), read_spec('SCENE_SPEC_PORTRAIT')
    reports = []
    if args.src:
        wide, report = build_landscape(args)
        reports.append((report, 'landscape'))
    if args.portrait:
        tall, report = build_portrait(args.portrait)
        reports.append((report, 'portrait'))
    if wide is None or tall is None:
        die(f'{os.path.relpath(SPEC, APP)} has no {"landscape" if wide is None else "portrait"} block yet and this run does not build one: pass both folders once')

    # ---- the spec the runtime reads --------------------------------------------------------------------------------
    header = (
        '// GENERATED by tools/build_scene_assets.py from the scene deliverables\' chain_layers.json (landscape and phone\n'
        '// sideways) and portrait_layers.json (portrait): do not edit by hand, rerun the tool when the scene renders change.\n'
        '// Every number is in px of that scene\'s FRAME (top-left origin).\n'
        '// SCENE_SPEC  points: per side the knocker\'s mouth pivot, where the hanging chain and the swag hook on the ring,\n'
        '//   the hanging chain\'s free end, the swag\'s lowest visible point (swagEnd) and its PIN, where it goes behind the\n'
        '//   bowl rim (read from the sprite). tiers: the texture sizes and each sprite\'s box (its atlas frame\n'
        '//   scene_<piece>_<side>_<set> covers exactly this box).\n'
        '// SCENE_SPEC_PORTRAIT  no moving pieces. painting / fill: the rows of the frame the painting takes and the rows of\n'
        '//   the soft mist fill under it, down to where the 3D terrace covers the frame (the board is meant to hide the fill).\n'
        '// components/Background.svelte and game/scene.ts draw from both.\n'
    )
    open(SPEC, 'w').write(header + 'export const SCENE_SPEC = ' + json.dumps(wide, indent='\t') + ' as const;\n\n'
                          + 'export const SCENE_SPEC_PORTRAIT = ' + json.dumps(tall, indent='\t') + ' as const;\n')
    print(f'wrote {os.path.relpath(SPEC, APP)}' + ('' if args.src and args.portrait else f' (the {"portrait" if args.src else "landscape"} block kept as it was)'))
    for report, what in reports:
        totals(report, what)


if __name__ == '__main__':
    main()
