#!/usr/bin/env python
"""Game assets for the animated win plaque ("stinger"): the layered cut-outs, every overlay sprite, the
baked titles and the forged glyph atlas, plus the motion tracks and the overlay recipes as runtime data.

  /Users/corey/Projects/stake-engine/math-sdk/env/bin/python tools/build_stinger_assets.py [--src DIR] [--reference FILE]

Sources (read only, never written), under --src (default ~/Desktop/Manticore Mayhem/images/ui):
  model/layered/stinger_layered.json + 15 PNGs at 2x     layers in z order, mesh topology, idle_all, the two flares, tier_gain
  model/stinger_{vein,glint,barb,eye_flare,embers}_fx.json, model/stinger_v5_eye_anchors.json     the overlay recipes
  drafts/stinger_{veins,glint,barb,eyes_v2,final_fx}_review/sprites/4x/*.png                      the overlay sprites
  drafts/text_assets/titles/*.png, plaque-glyphs.{png,json}, plaque-text.json                     tools/build_plaque_text.py

Outputs (static/assets/ui/stinger), everything regenerated by one run:
  stinger-<atlas>.json|webp        the FULL tier: plaque (the 15 cut-outs), fx (veins, slab, barbs, eyes, embers, star),
                                   glint (the 14 slices), titles, glyphs. Pixi spritesheet json, frames stg_<name>.
  stinger-<atlas>-half.json|webp   the PHONE tier twins (game/deviceTier.ts), same frame names
  stinger-motion.bin               int16 LE: per mesh layer idle_all (105 frames, absolute, 1/32 px) then tier_flare (22)
                                   and land_flare (31) deltas (linear: dx, dy; polar: theta, rho - 1; scales in the json)
  stinger.json                     everything the runtime reads: layers (uvs 0..1, indices, pivots, bin offsets, tier_gain),
                                   sprite rects, the five overlay recipes, barb tracks as idle + flare deltas, glyph
                                   metrics, kerning, title boxes, copy and the screen layouts

UNITS. Every position and size in stinger.json is in SHIP pixels of the 946 x 532 plaque frame (the "1x" of the source
notes), whatever resolution a texture ships at: `sprites[name]` = [x, y, w, h] is where the (trimmed) image sits, in frame
coordinates for placed sprites and relative to its anchor for anchored ones (barbs, star, eye flare, embers). The runtime
scales each sprite by w / texture width, so a tier is a file swap and nothing else.

RESOLUTION (TIERS below; the budget table at the end is the check, target about 24 MB of RGBA8 with mip chains):
the renderer caps the device pixel ratio at 1.5 and the plaque frame is about 0.4 of a desktop screen's width, so a ship
pixel is drawn at 0.55 (1280 wide at DPR 1) to about 1.3 device px (1920 at DPR 1.5, a tablet in portrait); a phone draws
it at 0.6 to 0.95. FULL ships the cut-outs, veins, titles and glyphs at 1.5x, PHONE at 1x. The glint slices are soft
highlights and the known hog (14 tall slices, 1.05 megapixels at 1x, 3 to 17 % filled, so a bbox trim gains nothing):
1x on FULL, 0.75x on PHONE, in their own atlas without a mip chain. Titles are baked at 3x of a 52.7 px cap and drawn
smaller (cap 50 / 32 / 36): each ships at the tier scale of its DRAWN size. The glyph atlas ships at the tier scale of
the largest use (the 64 px amount). Lids and embers are tiny and ship at 2x on both tiers (an ember is never drawn above
its native size), the vein wash and the slab mask (soft shapes) at 0.5x.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import struct
import sys
from fractions import Fraction
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
APP = HERE.parent
OUT = APP / "static" / "assets" / "ui" / "stinger"
SRC_DEFAULT = Path.home() / "Desktop" / "Manticore Mayhem" / "images" / "ui"

# texture px per ship px, by atlas group and tier
TIERS = {
    "": {"plaque": Fraction(3, 2), "fx": Fraction(3, 2), "glint": Fraction(1), "text": Fraction(3, 2)},
    "-half": {"plaque": Fraction(1), "fx": Fraction(1), "glint": Fraction(3, 4), "text": Fraction(1)},
}
FIXED = {"glow": Fraction(1, 2), "slab_dark": Fraction(1, 2), "eye": Fraction(2), "ember": Fraction(2)}
MIPS = {"plaque": True, "fx": True, "glint": False, "titles": True, "glyphs": True}
LOSSLESS = {"fx", "glint"}  # white + alpha: lossless is the small encoding
QUALITY = 92
PAD = 4  # transparent gutter around every frame (mip chains bleed)
TIER_NAMES = ["Big", "Super", "Mega", "Epic", "Max"]
IDLE_UNIT = 1 / 32  # ship px per int16 step of the absolute idle track
ALPHA_FLOOR = 2  # of 255: what a trim keeps


# ---- images ---------------------------------------------------------------------------------------
def load(path: Path) -> np.ndarray:
    return np.asarray(Image.open(path).convert("RGBA")).astype(np.float32) / 255.0


def resample(a: np.ndarray, w: int, h: int) -> np.ndarray:
    """straight RGBA float -> (h, w): filtered PREMULTIPLIED (no dark fringe), box when it is an integer reduction"""
    if (a.shape[1], a.shape[0]) == (w, h):
        return a
    pm = a.copy()
    pm[..., :3] *= pm[..., 3:4]
    box = a.shape[1] % w == 0 and a.shape[0] % h == 0
    chans = [np.asarray(Image.fromarray(pm[..., c], "F").resize((w, h), Image.BOX if box else Image.LANCZOS)) for c in range(4)]
    o = np.clip(np.stack(chans, -1), 0, 1)
    al = o[..., 3:4]
    o[..., :3] = np.where(al > 1e-5, o[..., :3] / np.maximum(al, 1e-5), 0)
    return np.clip(o, 0, 1)


def pad_to(a: np.ndarray, q: int) -> np.ndarray:
    h, w = a.shape[:2]
    H, W = -(-h // q) * q, -(-w // q) * q
    if (H, W) == (h, w):
        return a
    o = np.zeros((H, W, 4), np.float32)
    o[:h, :w] = a
    return o


def scaled(a: np.ndarray, src_scale: int, scale: Fraction, trim: bool):
    """A source image at src_scale px per ship px -> (image at `scale`, [x, y, w, h] in ship px relative to the
    source's top left). The crop is aligned so the result has whole pixels and the rect is exact."""
    f = scale / src_scale
    q = f.denominator
    h, w = a.shape[:2]
    x0 = y0 = 0
    if trim:
        ys, xs = np.nonzero(a[..., 3] > ALPHA_FLOOR / 255)
        if len(xs):
            x0, y0 = int(xs.min()) // q * q, int(ys.min()) // q * q
            a = a[y0 : int(ys.max()) + 1, x0 : int(xs.max()) + 1]
    a = pad_to(a, q)
    hh, ww = a.shape[:2]
    out = resample(a, int(ww * f), int(hh * f))
    return out, [x0 / src_scale, y0 / src_scale, ww / src_scale, hh / src_scale]


def pack(items: list[tuple[str, np.ndarray]]):
    """skyline (bottom-left) pack, tallest first; the width that gives the smallest sheet with both sides <= 2048 if
    one exists"""
    order = sorted(items, key=lambda it: (-it[1].shape[0], -it[1].shape[1]))
    best = None
    widest = max(im.shape[1] for _, im in items) + 2 * PAD
    for W in range(max(256, -(-widest // 32) * 32), 4097, 32):
        sky = [(0, W, 0)]  # (x, width, top) segments, left to right
        place = {}
        for name, im in order:
            h, w = im.shape[0] + 2 * PAD, im.shape[1] + 2 * PAD
            pick = None
            for i, (x, _, _) in enumerate(sky):
                if x + w > W:
                    break
                top, j, span = 0, i, 0
                while span < w:  # the highest segment under the frame
                    top = max(top, sky[j][2])
                    span += sky[j][1]
                    j += 1
                if pick is None or top < pick[0]:
                    pick = (top, x)
            top, x = pick
            place[name] = (x + PAD, top + PAD)
            nxt, done = [], False
            for sx, sw, st in sky:  # replace what the frame covers with one segment at its top
                if sx + sw <= x or sx >= x + w:
                    nxt.append((sx, sw, st))
                    continue
                if sx < x:
                    nxt.append((sx, x - sx, st))
                if not done:
                    nxt.append((x, w, top + h))
                    done = True
                if sx + sw > x + w:
                    nxt.append((x + w, sx + sw - x - w, st))
            sky = nxt
        H = max(t for _, _, t in sky)
        key = (max(W, H) > 2048, W * H)
        if best is None or key < best[0]:
            best = (key, W, H, place)
    _, W, H, place = best
    sheet = np.zeros((H, W, 4), np.float32)
    frames = {}
    for name, im in items:
        x, y = place[name]
        h, w = im.shape[:2]
        assert not sheet[y : y + h, x : x + w, 3].any(), name  # no overlap
        sheet[y : y + h, x : x + w] = im
        frames[name] = {"frame": {"x": x, "y": y, "w": w, "h": h}, "rotated": False, "trimmed": False, "spriteSourceSize": {"x": 0, "y": 0, "w": w, "h": h}, "sourceSize": {"w": w, "h": h}}
    return sheet, frames


BUDGET: list[tuple[str, int, int, bool, int, list[tuple[str, int]]]] = []


def write_atlas(group: str, suffix: str, items: list[tuple[str, np.ndarray]]):
    sheet, frames = pack(items)
    name = f"stinger-{group}{suffix}"
    img = Image.fromarray((sheet * 255 + 0.5).astype(np.uint8), "RGBA")
    path = OUT / f"{name}.webp"
    if group in LOSSLESS:
        img.save(path, "WEBP", lossless=True, quality=100, method=6)
    else:
        img.save(path, "WEBP", quality=QUALITY, method=6, alpha_quality=100)
    # meta.pngHash: the json's bytes (and so its ?v= stamp, which Pixi copies onto the image request) change whenever
    # the image does, as scripts/stamp-assets.mjs does for the atlases it lists
    meta = {"image": f"{name}.webp", "format": "RGBA8888", "size": {"w": img.width, "h": img.height}, "scale": "1", "pngHash": hashlib.md5(path.read_bytes()).hexdigest()[:8]}
    (OUT / f"{name}.json").write_text(json.dumps({"frames": frames, "meta": meta}, indent=1) + "\n")
    BUDGET.append((name, img.width, img.height, MIPS[group], path.stat().st_size, sorted(((n, im.shape[0] * im.shape[1]) for n, im in items), key=lambda t: -t[1])))


# ---- the build --------------------------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, default=SRC_DEFAULT, help="the images/ui folder of the Manticore working folder")
    ap.add_argument("--reference", type=Path, help="also write the python compositor's vertices for a few frames (tools/manticore/stinger_motion_check.mjs)")
    args = ap.parse_args()
    S: Path = args.src
    M, D, TA = S / "model", S / "drafts", S / "drafts" / "text_assets"
    OUT.mkdir(parents=True, exist_ok=True)
    lay = json.loads((M / "layered" / "stinger_layered.json").read_text())
    vein = json.loads((M / "stinger_vein_fx.json").read_text())
    glint = json.loads((M / "stinger_glint_fx.json").read_text())
    barb = json.loads((M / "stinger_barb_fx.json").read_text())
    eyes = json.loads((M / "stinger_v5_eye_anchors.json").read_text())
    flare = json.loads((M / "stinger_eye_flare_fx.json").read_text())
    emb = json.loads((M / "stinger_embers_fx.json").read_text())
    text = json.loads((TA / "plaque-text.json").read_text())
    assert lay["frame"] == [946, 532] and lay["texture_scale"] == 2 and lay["fps"] == 30
    assert [lay["actions"][a]["last_frame"] for a in ("idle_all", "land_flare", "tier_flare")] == [105, 30, 21]
    for doc in (vein, glint, barb, emb):
        assert [t["name"] for t in doc["tiers"]] == TIER_NAMES
    assert [t["name"] for t in flare["tiers"]] == TIER_NAMES

    sprites: dict[str, list[float]] = {}  # name -> [x, y, w, h] ship px
    r3 = lambda v: round(float(v), 3)

    def rect(name, box, ox=0.0, oy=0.0):
        sprites[name] = [r3(box[0] + ox), r3(box[1] + oy), r3(box[2]), r3(box[3])]

    # ---- the layered plaque: textures, topology, tracks ------------------------------------------
    by = {L["name"]: L for L in lay["layers"]}
    plaque_src = {L["name"]: load(M / "layered" / L["texture"]) for L in lay["layers"]}
    layers_out, blob, off, art_boxes = [], [], 0, []
    for L in lay["layers"]:
        n = L["name"]
        tw, th = L["size"]
        assert plaque_src[n].shape[:2] == (th, tw), n
        # the cut-outs are padded (right / bottom) to a multiple of 4 source px so they resample to whole pixels
        pw, ph = -(-tw // 4) * 4, -(-th // 4) * 4
        ys, xs = np.nonzero(plaque_src[n][..., 3] > 0.5)  # the solid art, texture px
        if L["type"] == "static":
            layers_out.append({"name": n, "type": "static", "frame": f"stg_{n}"})
            rect(n, [L["pos"][0], L["pos"][1], pw / 2, ph / 2])
            art_boxes.append([L["pos"][0] + xs.min() / 2, L["pos"][1] + ys.min() / 2, L["pos"][0] + (xs.max() + 1) / 2, L["pos"][1] + (ys.max() + 1) / 2])
            continue
        G = by[L["share"]] if "share" in L else L  # the back sheets draw the front sheet's geometry
        nv = len(G["uvs"]) // 2
        entry = {"name": n, "type": "mesh", "frame": f"stg_{n}", "nv": nv}
        if "share" in L:
            assert L["size"] == G["size"] and L["pivot"] == G["pivot"] and L["flares"] == G["flares"], n
            entry["share"] = L["share"]
            layers_out.append(entry)
            continue
        assert L["type"] == "mesh" and L["add"] in ("linear", "polar")
        # at the bind pose a mover's texture is a plain translation of its cut-out: its solid art joins the art box
        o = np.array(L["bind"], np.float64).reshape(-1, 2) - np.array(L["uvs"], np.float64).reshape(-1, 2) / 2
        assert np.abs(o - o.mean(0)).max() < 0.01, n
        art_boxes.append([o[0, 0] + xs.min() / 2, o[0, 1] + ys.min() / 2, o[0, 0] + (xs.max() + 1) / 2, o[0, 1] + (ys.max() + 1) / 2])
        uv = np.array(L["uvs"], np.float64).reshape(-1, 2) / [pw, ph]
        idle = np.array(L["frames"]["idle_all"], np.float64)
        assert idle.shape == (106, nv * 2) and np.abs(idle[105] - idle[0]).max() == 0  # frame 105 is frame 0
        q = np.round(idle[:105] / IDLE_UNIT)
        assert np.abs(q).max() < 32767
        entry.update(add=L["add"], pivot=L["pivot"], uvs=[round(float(v), 6) for v in uv.ravel()], indices=L["indices"], bind=[r3(v) for v in L["bind"]], idle={"offset": off, "unit": IDLE_UNIT})
        blob.append(q.astype("<i2").ravel())
        off += q.size
        for action, frames in (("tier_flare", 22), ("land_flare", 31)):
            d = np.array(L["flares"][action]["frames"], np.float64).reshape(frames, nv, 2)
            if action == "land_flare":
                assert L["flares"][action]["idle_start"] == 75
            if L["add"] == "polar":
                d[..., 1] -= 1.0  # rho -> rho - 1, so "no flare" is 0 in both components
            unit = [max(float(np.abs(d[..., c]).max()), 1e-9) / 32767 for c in (0, 1)]
            qd = np.round(d / unit)
            assert np.abs(qd[-1]).max() == 0, (n, action, "the flare must end on the idle")
            entry["tier" if action == "tier_flare" else "land"] = {"offset": off, "unit": unit}
            blob.append(qd.astype("<i2").ravel())
            off += qd.size
        gain = lay.get("tier_gain", {}).get(n)
        if gain and min(gain) < 1:
            assert len(gain) == 105
            entry["gain"] = gain
        layers_out.append(entry)
    (OUT / "stinger-motion.bin").write_bytes(np.concatenate(blob).tobytes())

    # ---- overlay sources at 4x ---------------------------------------------------------------------
    def fx_items(t):
        items = []

        def add(name, path, scale, origin, trim=True, anchored=False):
            img, box = scaled(load(path), 4, scale, trim)
            items.append((f"stg_{name}", img))
            rect(name, box, 0 if anchored else origin[0], 0 if anchored else origin[1])
            if anchored:  # the rect is relative to the anchor
                sprites[name][0] = r3(box[0] - origin[0])
                sprites[name][1] = r3(box[1] - origin[1])

        vs = D / "stinger_veins_review" / "sprites" / "4x"
        vo = vein["sprites"]["top_left_px_1x"]
        assert vein["slab_dark"]["top_left_px_1x"] == vo and vein["sprites"]["size_px_1x"] == vein["slab_dark"]["size_px_1x"]
        for f in vein["sprites"]["veins"]:
            add(f[:-4], vs / f, t["fx"], vo)
        add("glow", vs / vein["sprites"]["glow"], FIXED["glow"], vo)
        add("slab_dark", vs / vein["slab_dark"]["file"], FIXED["slab_dark"], vo)
        bs = D / "stinger_barb_review" / "sprites" / "4x"
        for side in "LR":
            sp = barb["sprites"][side]
            for kind in ("halo", "highlight"):
                add(sp[kind][:-4], bs / sp[kind], t["fx"], sp["anchor_px_1x"], anchored=True)
        es = D / "stinger_eyes_v2_review" / "sprites" / "4x"
        for eye, e in eyes["eyes"].items():
            for fr, f in e["sprites"]["lid_frames"].items():
                add(f[:-4], es / f, FIXED["eye"], e["sprites"]["lid_top_left_px_1x"], trim=False)
            for fr, f in e["sprites"]["glow_additive_frames"].items():
                add(f[:-4], es / f, FIXED["eye"], e["sprites"]["glow_top_left_px_1x"], trim=False)
        fs = D / "stinger_final_fx_review" / "sprites" / "4x"
        for key in ("bloom", "streak"):
            sp = flare["sprites"][key]
            add(sp["file"][:-4], fs / sp["file"], t["fx"], [sp["size_px_1x"][0] / 2, sp["size_px_1x"][1] / 2], trim=False, anchored=True)
        for name in ("ember_dot", "ember_flake", "ember_hot", "ember_spark", "ember_streak"):
            w, h = emb["sprites"][name]
            add(name, fs / f"{name}.png", FIXED["ember"], [w / 2, h / 2], trim=False, anchored=True)
        gs = D / "stinger_glint_review" / "sprites" / "4x"
        st = glint["sprites"]["star"]
        add("star", gs / st["file"], t["fx"], [st["size_px_1x"][0] / 2, st["size_px_1x"][1] / 2], trim=False, anchored=True)
        return items

    def glint_items(t):
        items = []
        gs = D / "stinger_glint_review" / "sprites" / "4x"
        for sl in glint["sprites"]["slices"]:
            img, box = scaled(load(gs / sl["file"]), 4, t["glint"], True)
            items.append((f"stg_{sl['file'][:-4]}", img))
            rect(sl["file"][:-4], box, *sl["top_left_px_1x"])
        return items

    # ---- text --------------------------------------------------------------------------------------
    LAYT = text["layout"]
    title_cap = lambda name: LAYT["intro" if name.startswith("intro_") else "win" if name.startswith("win_") else "wrap"]["title_cap"]
    GLYPH_FULL = max(LAYT["win"]["amount_px"], LAYT["wrap"]["amount_px"], LAYT["intro"]["text_px"], LAYT["wrap"]["line_px"])
    gsheet = load(TA / "plaque-glyphs.png")
    gframes = json.loads((TA / "plaque-glyphs.json").read_text())["frames"]
    glyphs = {}
    for ch, g in text["text"]["glyphs"].items():
        if not g.get("frame"):
            glyphs[ch] = [g["adv"]]
            continue
        fr = gframes[g["frame"]]["frame"]
        assert (fr["w"], fr["h"]) == (g["w"], g["h"])
        # w / h grow to the padded cell (a multiple of 6 atlas px: whole pixels at both tier scales)
        glyphs[ch] = [g["adv"], g["ox"], g["oy"], -(-g["w"] // 6) * 6, -(-g["h"] // 6) * 6, f"stg_g_{ord(ch):04x}"]

    def text_items(t):
        titles, gl = [], []
        for name, T in text["titles"].items():
            f = float(t["text"]) * title_cap(name) / T["cap"]
            img = load(TA / "titles" / f"{name}.png")
            assert (img.shape[1], img.shape[0]) == (T["w"], T["h"]), name
            titles.append((f"stg_title_{name}", resample(img, max(1, round(T["w"] * f)), max(1, round(T["h"] * f)))))
            if "glow" in T:
                g = load(TA / "titles" / f"{name}_glow.png")
                assert (g.shape[1], g.shape[0]) == (T["glow"]["w"], T["glow"]["h"]), name
                titles.append((f"stg_title_{name}_glow", resample(g, max(1, round(g.shape[1] * f / 2)), max(1, round(g.shape[0] * f / 2)))))  # a soft halo: half scale
        f = t["text"] * GLYPH_FULL / text["text"]["em"]
        assert f.denominator in (1, 2, 3, 6), f
        for ch, g in text["text"]["glyphs"].items():
            if not g.get("frame"):
                continue
            fr = gframes[g["frame"]]["frame"]
            cell = pad_to(gsheet[fr["y"] : fr["y"] + fr["h"], fr["x"] : fr["x"] + fr["w"]], 6)
            gl.append((glyphs[ch][5], resample(cell, int(cell.shape[1] * f), int(cell.shape[0] * f))))
        return titles, gl

    for suffix, t in TIERS.items():
        items = []
        for L in lay["layers"]:
            src = pad_to(plaque_src[L["name"]], 4)
            f = t["plaque"] / 2
            items.append((f"stg_{L['name']}", resample(src, int(src.shape[1] * f), int(src.shape[0] * f))))
        write_atlas("plaque", suffix, items)
        write_atlas("fx", suffix, fx_items(t))
        write_atlas("glint", suffix, glint_items(t))
        titles, gl = text_items(t)
        write_atlas("titles", suffix, titles)
        write_atlas("glyphs", suffix, gl)

    # ---- recipes -----------------------------------------------------------------------------------
    def barb_tracks(side):
        idle = np.array(barb["tracks"]["idle_all"][side], np.float64)
        tier = np.array(barb["tracks"]["tier_flare"][side], np.float64)
        land = np.array(barb["tracks"]["land_flare"][side], np.float64)
        assert idle.shape == (105, 7) and tier.shape == (22, 7) and land.shape == (31, 7)
        assert np.abs(tier[0] - idle[0]).max() == 0  # tier_flare is authored from idle frame 0
        # the same additive model as the meshes: tier delta = tier[g] - idle[0], land delta = land[g] - idle[75 + g]
        td = tier[:, :4] - idle[0, :4]
        ld = land[:, :4] - idle[(75 + np.arange(31)) % 105, :4]
        td[-1] = 0  # the flares end on the idle (the tracks' last rows are within the fit's noise of it)
        ld[-1] = 0
        rnd = lambda a: [round(float(v), 4) for v in a.ravel()]
        return {"idle": rnd(idle[:, :5]), "tier": rnd(td), "land": rnd(ld), "landVisibility": rnd(land[:, 4])}

    eye_out = {}
    for eye, e in eyes["eyes"].items():
        fl = flare["eyes"][eye]
        eye_out[eye] = {
            "centre": fl["centre_px_1x"], "delay": fl["delay_s"], "size": fl["size"], "streakRot": fl["streak_rot_deg"], "slant": e["slant_deg"],
            "lids": {k: v[:-4] for k, v in e["sprites"]["lid_frames"].items()},
            "glows": {k: v[:-4] for k, v in e["sprites"]["glow_additive_frames"].items()},
        }
    regions = [r["name"] for r in emb["regions"]]

    def ember_row(p, burst=False):
        row = [regions.index(p["region"]), p["fx"], p["fy"], p["speed"], p["sway_amp"], p["sway_hz"], p["sway_phase"], p["life"], p["delay"] if burst else p["period"], 0 if burst else p["offset"], p["size"], p["kind"], ["ember_dot", "ember_flake"].index(p["base_sprite"]), p["heat"], p["twinkle_hz"]]
        return row, p.get("points")

    def ember_table(rows, burst=False):
        out, pts = [], []
        for p in rows:
            row, points = ember_row(p, burst)
            assert (points is not None) == (p["region"] == "panel_cracks")
            out.append(row)
            pts.append([v for xy in points for v in xy] if points else 0)
        return {"rows": out, "points": pts}

    data = {
        "note": "GENERATED by tools/build_stinger_assets.py from the approved plaque sources: do not edit, rerun the tool. Ship px of the 946 x 532 frame.",
        "frame": lay["frame"],
        # the bind pose art's box (all 15 cut-outs, alpha above one half): what the layout fits between the chains
        "art": [r3(min(b[0] for b in art_boxes)), r3(min(b[1] for b in art_boxes)), r3(max(b[2] for b in art_boxes)), r3(max(b[3] for b in art_boxes))],
        "fps": lay["fps"],
        "tiers": [n.lower() for n in TIER_NAMES],
        "motion": {"idleFrames": 105, "tierFrames": 22, "landFrames": 31, "landIdleStart": 75, "layers": layers_out},
        "sprites": sprites,
        "vein": {
            "sprites": [f[:-4] for f in vein["sprites"]["veins"]], "glow": "glow", "slab": "slab_dark", "slabAlpha": vein["slab_dark"]["alpha"],
            "tiers": [{"base": t["base_alpha"], "peak": t["peak_alpha"], "period": t["period_s"], "tint": t["tint_rgb"], "glow": t["glow_alpha"]} for t in vein["tiers"]],
        },
        "glint": {
            "tint": glint["sprites"]["tint_rgb"], "starTint": glint["sprites"]["star"]["tint_rgb"],
            "slices": [{"sprite": s["file"][:-4], "s": s["s"]} for s in glint["sprites"]["slices"]],
            "halfWidth": glint["sweep"]["half_width"], "idleDuration": glint["sweep"]["idle_duration_s"], "landingDuration": glint["sweep"]["landing_duration_s"], "landingPeak": glint["sweep"]["landing_peak_alpha"],
            "sites": [{"x": s["centre_px_1x"][0], "y": s["centre_px_1x"][1], "s": s["sweep_s"], "scale": s["max_scale"]} for s in glint["stars"]["sites"]],
            "starLife": glint["stars"]["life_s"], "landingPick": glint["stars"]["landing_pick"], "landingExtraDelay": glint["stars"]["landing_extra_delay_s"],
            "tiers": [{"interval": t["sweep_interval_s"], "peak": t["peak_alpha"], "stars": t["stars"]} for t in glint["tiers"]],
        },
        "barb": {
            "sides": {side: {"halo": barb["sprites"][side]["halo"][:-4], "highlight": barb["sprites"][side]["highlight"][:-4], "phase": barb["pulse"]["phase_rad"][side], **barb_tracks(side)} for side in "LR"},
            "tiers": [{"base": t["base_alpha"], "peak": t["peak_alpha"], "period": t["period_s"], "tint": t["tint_rgb"], "halo": t["halo_alpha"]} for t in barb["tiers"]],
        },
        "eyes": {
            "eyes": eye_out,
            "blink": {"sequence60": [["open", "quarter", "half", "three_quarter", "closed"].index(k) for k in eyes["blink"]["sequence_60fps"]], "timing": eyes["blink"]["timing_ms"]},
            "flare": {"duration": flare["duration_s"], "attack": flare["attack_s"], "bloom": flare["sprites"]["bloom"]["file"][:-4], "streak": flare["sprites"]["streak"]["file"][:-4], "tiers": [{"gain": t["gain"], "size": t["size"]} for t in flare["tiers"]]},
        },
        "embers": {
            "sprites": ["ember_dot", "ember_flake", "ember_hot", "ember_spark", "ember_streak"],
            "columns": ["region", "fx", "fy", "speed", "swayAmp", "swayHz", "swayPhase", "life", "period (loop) / delay (burst)", "offset", "size", "kind", "baseSprite", "heat", "twinkleHz"],
            "regions": [{"name": r["name"], "panel": r["layer"] == "panel", "rect": r["rect"], "killY": r["kill_y"]} for r in emb["regions"]],
            "exclusions": [r["rect"] for r in emb["exclusions"]],
            "textZone": emb["text_zone"],
            "tiers": [{"slots": t["slots"], "speed": t["speed"], "alpha": t["alpha"], "twinkle": t["twinkle"], "spark": t["spark_share"], "streak": t["streak_share"], "hot": t["hot_share"], "cool": t["tint_cool"], "warm": t["tint_hot"]} for t in emb["tiers"]],
            "loop": ember_table(emb["particles"]),
            "bursts": [ember_table(emb["burst_particles"][n], True) for n in TIER_NAMES],
        },
        "text": {
            "em": text["text"]["em"], "cap": text["text"]["cap"], "glyphs": glyphs, "kern": text["text"]["kern"],
            "titles": {n: {"frame": f"stg_title_{n}", "text": T["text"], "w": T["w"], "h": T["h"], "baseline": T["baseline"], "cap": T["cap"], **({"glow": T["glow"]} if "glow" in T else {})} for n, T in text["titles"].items()},
            "copy": text["copy"],
            "layout": LAYT,
        },
    }
    assert max(t["slots"] for t in emb["tiers"]) <= len(emb["particles"])
    (OUT / "stinger.json").write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n")

    if args.reference:
        write_reference(M, args.reference)

    # ---- the budget table ----------------------------------------------------------------------------
    print("art box (bind pose, ship px):", data["art"])
    print(f"motion: {off} int16 = {off * 2 / 1024:.0f} KB, stinger.json {(OUT / 'stinger.json').stat().st_size / 1024:.0f} KB")
    for suffix, label in (("", "FULL tier"), ("-half", "PHONE tier")):
        print(f"\n{label}: texture, size, megapixels, MB as RGBA8 (with its mip chain), file")
        tot = totm = totf = 0
        for name, w, h, mips, size, parts in BUDGET:
            if name.endswith("-half") != bool(suffix):
                continue
            mb = w * h * 4 / 1048576
            mbm = mb * (4 / 3 if mips else 1)
            tot, totm, totf = tot + mb, totm + mbm, totf + size
            big = ", ".join(f"{n[4:]} {p / 1e6:.2f}" for n, p in parts[:4])
            print(f"  {name:24s} {w:4d} x {h:4d}  {w * h / 1e6:5.2f} Mpx  {mb:5.2f} MB ({mbm:5.2f}{'' if mips else ', no mips'})  {size / 1024:5.0f} KB   largest: {big}")
        print(f"  {'total':24s} {'':11s}  {'':9s}  {tot:5.2f} MB ({totm:5.2f} with mips)  {totf / 1024:5.0f} KB")


def write_reference(M: Path, path: Path) -> None:
    """the reference compositor's vertices (model/scripts/L0_lib.py Layered.layer_mesh, 1x px) for the node self check"""
    sys.path.insert(0, str(M / "scripts"))
    import L0_lib  # noqa: E402

    Ld = L0_lib.Layered(str(M / "layered" / "stinger_layered.json"))
    cases = [("idle_all", 0, None), ("idle_all", 17, None), ("idle_all", 104, None), ("land_flare", 0, None), ("land_flare", 6, None), ("land_flare", 30, None), ("tier_flare", 4, 0), ("tier_flare", 7, 53), ("tier_flare", 12, 95), ("tier_flare", 21, 100)]
    out = []
    for action, f, P in cases:
        for name in L0_lib.MOVERS:
            L = Ld.by[name]
            gain = Ld.J.get("tier_gain", {}).get(name, [1.0] * 105)[P] if P is not None else 1.0
            v, _, _ = Ld.layer_mesh(L, action, f, P, gain)
            out.append({"action": action, "frame": f, "idleFrom": P, "layer": name, "vertices": [round(float(x), 4) for x in (np.asarray(v) / Ld.J["texture_scale"]).ravel()]})
    path.write_text(json.dumps(out))
    print(f"reference: {len(out)} layer poses -> {path}")


if __name__ == "__main__":
    main()
