#!/usr/bin/env python
"""Game assets for the logo: the static stacked logo (an HTML <img> on the phone tier, on the landing screen and as the
desktop stand-in) and the animated one the desktop draws in the canvas (components/Logo.svelte, game/logo/).

  /Users/corey/Projects/stake-engine/math-sdk/env/bin/python tools/build_logo_assets.py [--src DIR]
  node scripts/stamp-assets.mjs          (afterwards, from the app folder)

Source (read only, never written), --src (default ~/Desktop/Manticore Mayhem/images/ui/drafts/logo_review_6):
  logo_stacked.png                         the approved still, 2400 px wide, transparent
  layered/logo_stacked_layered.json + PNGs the same logo in layers at 2x: two wing meshes with their idle_breathe (135
                                           frames), flare (22) and entrance (34) tracks, the letter shadow, the letters,
                                           10 gold + 8 red glint slices (see layered/README.md)

Outputs, everything regenerated by one run:
  static/assets/ui/logo-stacked.webp       the still cropped to its art, STATIC_WIDTH px wide (the largest HTML use is
                                           about 405 CSS px on a 3x phone and 570 CSS px at 2x on a desktop landing screen)
  static/assets/ui/logo/logo.json|webp     ONE atlas, frames logo_<name>: the wings and letters at 1.5 texture px per ship
                                           px, the letter shadow at 0.75, the baked drop shadow at 0.25, the glint slices
                                           at 1 as WHITE + alpha (the runtime tints them)
  static/assets/ui/logo/logo-motion.bin    int16 LE per wing: the bind pose and the idle key frames (absolute, 1/40 ship
                                           px), then the flare (theta only, the source's rho is 1 throughout)
  static/assets/ui/logo/logo-data.json     what the runtime reads: mesh topology, pivots, bin offsets, the entrance tracks,
                                           sprite rects, the glint recipe and where the still's art sits in the frame

UNITS. Everything in logo-data.json is in SHIP px of the 754 x 420 logo frame. `art` is the still's art box in that
frame: the HTML logo's box IS that box, so the canvas logo is placed by mapping `art` onto the same rectangle
(game/logo/layout.ts). It is found here by fitting the still onto the bind pose composite of the layers.

WHAT IS CUT, and the checks this script prints:
  idle keys    the breathing is slow (0.08 to 0.26 ship px a frame), so only every IDLE_STEP-th frame ships and the runtime
               interpolates. The largest error against the 135 source frames is printed and asserted under IDLE_TOLERANCE.
  glint        the slices are one flat colour with an alpha, so they ship as white + alpha at 1 texture px per ship px
               (the source is 2): a quarter of the texels. The sum of a sweep rebuilt from the shipped slices is compared
               with the source's at every sweep position; the largest difference is printed.
  drop shadow  the HTML logo wears drop-shadow(0 4px 8px rgba(0,0,0,0.7)); the canvas has no filters (house rule), so the
               same shadow is baked from the still's silhouette at a quarter resolution and drawn under the wings.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from fractions import Fraction
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import build_stinger_assets as B  # noqa: E402  (load, resample, scaled, pack: the plaque's own image helpers)

APP = HERE.parent
UI = APP / "static" / "assets" / "ui"
OUT = UI / "logo"
SRC_DEFAULT = Path.home() / "Desktop" / "Manticore Mayhem" / "images" / "ui" / "drafts" / "logo_review_6"

FRAME = [754, 420]
SRC_SCALE = 2
STATIC_WIDTH = 1200
STATIC_QUALITY = 90
# texture px per ship px. The art is drawn 300 master px wide for 690.9 ship px, so a ship px is 0.43 device px on a
# 1280 x 720 window at DPR 1 and 1.30 on 1920 x 1080 at the renderer's cap of 2: 1.5 covers it, with a mip chain below.
SCALE = {"wing": Fraction(3, 2), "letters": Fraction(3, 2), "shadow": Fraction(3, 4), "glint": Fraction(1), "drop": Fraction(1, 4)}
QUALITY = 92
UNIT = 1 / 40  # ship px per int16 step of the bind pose and the idle keys
IDLE_STEP = 3  # every 3rd of the 135 idle frames ships (45 keys, 10 a second)
IDLE_TOLERANCE = 0.03  # ship px: the largest error the interpolation may make against the source frames
# the HTML logo's CSS drop shadow, in master px at the width it was authored for (the landscape chrome)
DROP = {"offset_y": 4.0, "blur": 8.0, "alpha": 0.7, "at_art_width": 300.0, "margin": 40}
N_IDLE, N_FLARE, N_ENTER = 135, 22, 34
r3 = lambda v: round(float(v), 3)
r5 = lambda v: round(float(v), 5)


def bbox(alpha: np.ndarray, floor: float):
    ys, xs = np.nonzero(alpha > floor)
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def over(dst: np.ndarray, x: int, y: int, src: np.ndarray) -> None:
    """premultiplied src over dst, in place"""
    h, w = src.shape[:2]
    d = dst[y : y + h, x : x + w]
    d *= 1 - src[..., 3:4]
    d += src


def raster_mesh(shape, tex, verts, uvs, tris):
    """a textured triangle mesh into a premultiplied buffer (pixel centre sampling, nearest texel: only its coverage is
    used here, to register the still)"""
    H, W = shape
    out = np.zeros((H, W, 4), np.float32)
    th, tw = tex.shape[:2]
    for t in tris:
        p, q = verts[t], uvs[t]
        x0, x1 = max(int(np.floor(p[:, 0].min())), 0), min(int(np.ceil(p[:, 0].max())) + 1, W)
        y0, y1 = max(int(np.floor(p[:, 1].min())), 0), min(int(np.ceil(p[:, 1].max())) + 1, H)
        den = (p[1, 1] - p[2, 1]) * (p[0, 0] - p[2, 0]) + (p[2, 0] - p[1, 0]) * (p[0, 1] - p[2, 1])
        if x1 <= x0 or y1 <= y0 or abs(den) < 1e-9:
            continue
        X, Y = np.meshgrid(np.arange(x0, x1) + 0.5, np.arange(y0, y1) + 0.5)
        l0 = ((p[1, 1] - p[2, 1]) * (X - p[2, 0]) + (p[2, 0] - p[1, 0]) * (Y - p[2, 1])) / den
        l1 = ((p[2, 1] - p[0, 1]) * (X - p[2, 0]) + (p[0, 0] - p[2, 0]) * (Y - p[2, 1])) / den
        l2 = 1 - l0 - l1
        ins = (l0 >= -1e-6) & (l1 >= -1e-6) & (l2 >= -1e-6)
        u = np.clip((l0 * q[0, 0] + l1 * q[1, 0] + l2 * q[2, 0]).astype(int), 0, tw - 1)
        v = np.clip((l0 * q[0, 1] + l1 * q[1, 1] + l2 * q[2, 1]).astype(int), 0, th - 1)
        out[y0:y1, x0:x1][ins] = tex[v[ins], u[ins]]
    return out


def premult(a: np.ndarray) -> np.ndarray:
    o = a.copy()
    o[..., :3] *= o[..., 3:4]
    return o


def register_still(still: np.ndarray, lay: dict, src: dict[str, np.ndarray]):
    """where the still sits in the ship frame: [x, y, w, h] of the WHOLE png, by fitting its alpha onto the bind pose
    composite of the layers at 2x (scale searched around the ratio of the two alpha boxes, offset to the pixel)"""
    k = SRC_SCALE
    W, H = FRAME[0] * k, FRAME[1] * k
    comp = np.zeros((H, W, 4), np.float32)
    for L in lay["layers"]:
        t = premult(src[L["name"]])
        if L["type"] == "mesh":
            v = np.array(L["bind"], np.float32).reshape(-1, 2) * k
            over(comp, 0, 0, raster_mesh((H, W), t, v, np.array(L["uvs"], np.float32).reshape(-1, 2), np.array(L["indices"]).reshape(-1, 3)))
        else:
            over(comp, int(round(L["pos"][0] * k)), int(round(L["pos"][1] * k)), t)
    ca = comp[..., 3]
    cb, sb = bbox(ca, 0.5), bbox(still[..., 3], 0.5)
    guess = (sb[2] - sb[0]) / (cb[2] - cb[0])
    best = None
    for s in np.linspace(guess - 0.004, guess + 0.004, 9):
        w, h = int(round(still.shape[1] / s)), int(round(still.shape[0] / s))
        a = np.asarray(Image.fromarray(still[..., 3], "F").resize((w, h), Image.LANCZOS))
        ab = bbox(a, 0.5)
        for dx in range(-2, 3):
            for dy in range(-2, 3):
                ox, oy = cb[0] - ab[0] + dx, cb[1] - ab[1] + dy
                x0, y0, x1, y1 = max(ox, 0), max(oy, 0), min(ox + w, W), min(oy + h, H)
                d = float(np.abs(ca[y0:y1, x0:x1] - a[y0 - oy : y1 - oy, x0 - ox : x1 - ox]).mean())
                if best is None or d < best[0]:
                    best = (d, ox, oy, w, h)
    d, ox, oy, w, h = best
    print(f"still registration: whole png at ship x {ox / k} y {oy / k} w {w / k} h {h / k} (mean alpha difference to the bind composite {d * 255:.2f} / 255)")
    return [ox / k, oy / k, w / k, h / k]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, default=SRC_DEFAULT, help="the logo review folder (logo_stacked.png and layered/)")
    args = ap.parse_args()
    S: Path = args.src
    LAY = S / "layered"
    OUT.mkdir(parents=True, exist_ok=True)
    lay = json.loads((LAY / "logo_stacked_layered.json").read_text())
    assert lay["frame"] == FRAME and lay["texture_scale"] == SRC_SCALE and lay["fps"] == 30
    assert [lay["actions"][a]["last_frame"] for a in ("idle_breathe", "flare", "entrance")] == [N_IDLE, N_FLARE - 1, N_ENTER - 1]
    assert [L["name"] for L in lay["layers"]] == ["wing_L", "wing_R", "shadow", "letters"]
    src = {L["name"]: B.load(LAY / L["texture"]) for L in lay["layers"]}
    still = B.load(S / "logo_stacked.png")

    # ---- the static logo: the still cropped to its art ---------------------------------------------
    whole = register_still(still, lay, src)
    per = whole[2] / still.shape[1]  # ship px per still px
    x0, y0, x1, y1 = bbox(still[..., 3], B.ALPHA_FLOOR / 255)
    art = [whole[0] + x0 * per, whole[1] + y0 * per, (x1 - x0) * per, (y1 - y0) * per]
    crop = still[y0:y1, x0:x1]
    sh = round(STATIC_WIDTH * crop.shape[0] / crop.shape[1])
    static = B.resample(crop, STATIC_WIDTH, sh)
    static_path = UI / "logo-stacked.webp"
    Image.fromarray((static * 255 + 0.5).astype(np.uint8), "RGBA").save(static_path, "WEBP", quality=STATIC_QUALITY, method=6, alpha_quality=100)
    print(f"logo-stacked.webp {STATIC_WIDTH} x {sh} (aspect {STATIC_WIDTH / sh:.4f}), {static_path.stat().st_size / 1024:.0f} KB; art box in ship px {[r3(v) for v in art]} (aspect {art[2] / art[3]:.4f})")

    sprites: dict[str, list[float]] = {}
    items: list[tuple[str, np.ndarray]] = []

    def add(name: str, image: np.ndarray, scale: Fraction, pos, trim: bool = False) -> None:
        out, box = B.scaled(image, SRC_SCALE, scale, trim)
        sprites[name] = [r3(pos[0] + box[0]), r3(pos[1] + box[1]), r3(box[2]), r3(box[3])]
        items.append((f"logo_{name}", out))

    # ---- the baked drop shadow: the still's silhouette, offset and blurred as the CSS filter does ------
    m = DROP["margin"]
    ship = art[2] / DROP["at_art_width"]  # ship px per master px
    canvas = np.zeros((FRAME[1] + 2 * m, FRAME[0] + 2 * m), np.float32)
    sw, shh = round(whole[2]), round(whole[3])
    a1 = np.clip(np.asarray(Image.fromarray(still[..., 3], "F").resize((sw, shh), Image.LANCZOS)), 0, 1)
    ox, oy = round(whole[0]) + m, round(whole[1] + DROP["offset_y"] * ship) + m
    canvas[oy : oy + shh, ox : ox + sw] = a1
    blurred = gaussian_filter(canvas, DROP["blur"] / 2 * ship) * DROP["alpha"]
    drop = np.zeros(blurred.shape + (4,), np.float32)
    drop[..., 3] = blurred
    drop_small, _ = B.scaled(drop, 1, SCALE["drop"], False)
    sprites["drop"] = [-m, -m, drop.shape[1], drop.shape[0]]
    items.append(("logo_drop", drop_small))

    # ---- the layers: textures, topology, tracks ---------------------------------------------------
    layers_out, blob, off = [], [], 0
    for L in lay["layers"]:
        n = L["name"]
        tw, th = L["size"]
        assert src[n].shape[:2] == (th, tw), n
        E = L["flares"]["entrance"]
        if L["type"] == "static":
            add(n, src[n], SCALE[n], L["pos"])
            assert len(E["scale"]) == N_ENTER and len(E["alpha"]) == N_ENTER and E["scale"][-1] == 1 and E["alpha"][-1] == 1
            layers_out.append({"name": n, "type": "static", "frame": f"logo_{n}", "entrance": {"pivot": E["pivot"], "scale": [r5(v) for v in E["scale"]], "alpha": [r5(v) for v in E["alpha"]]}})
            continue
        assert L["type"] == "mesh" and L["add"] == "polar"
        out, box = B.scaled(src[n], SRC_SCALE, SCALE["wing"], False)
        items.append((f"logo_{n}", out))
        pw, ph = box[2] * SRC_SCALE, box[3] * SRC_SCALE  # the padded source size the uvs are normalised by
        nv = len(L["uvs"]) // 2
        uv = np.array(L["uvs"], np.float64).reshape(-1, 2) / [pw, ph]
        bind = np.array(L["bind"], np.float64)
        idle = np.array(L["frames"]["idle_breathe"], np.float64)
        assert idle.shape == (N_IDLE, nv * 2) and bind.shape == (nv * 2,)
        keys = idle[::IDLE_STEP]
        assert N_IDLE % IDLE_STEP == 0 and np.abs(keys).max() / UNIT < 32767
        qk = np.round(keys / UNIT)
        # what the runtime will draw on every source frame: the quantised keys, interpolated, the loop closed
        K = len(qk)
        f = np.arange(N_IDLE) / IDLE_STEP
        a = np.floor(f).astype(int)
        w = (f - a)[:, None]
        rebuilt = (qk[a % K] * (1 - w) + qk[(a + 1) % K] * w) * UNIT
        err = float(np.abs(rebuilt - idle).max())
        assert err < IDLE_TOLERANCE, (n, err)
        entry = {"name": n, "type": "mesh", "frame": f"logo_{n}", "nv": nv, "pivot": L["pivot"], "uvs": [round(float(v), 6) for v in uv.ravel()], "indices": L["indices"]}
        entry["bind"] = {"offset": off}
        blob.append(np.round(bind / UNIT).astype("<i2"))
        off += bind.size
        entry["idle"] = {"offset": off}
        blob.append(qk.astype("<i2").ravel())
        off += qk.size
        d = np.array(L["flares"]["flare"]["frames"], np.float64).reshape(N_FLARE, nv, 2)
        assert np.abs(d[..., 1] - 1).max() == 0, (n, "the flare is a rotation only: rho must be 1")
        assert np.abs(d[0, :, 0]).max() == 0 and np.abs(d[-1, :, 0]).max() == 0, (n, "the flare must start and end on the idle")
        unit = float(np.abs(d[..., 0]).max()) / 32767
        entry["flare"] = {"offset": off, "unit": unit}
        blob.append(np.round(d[..., 0] / unit).astype("<i2").ravel())
        off += N_FLARE * nv
        assert E["uniform"] and E["idle_start"] == 0 and len(E["frames"]) == N_ENTER and len(E["alpha"]) == N_ENTER
        assert E["frames"][-1][1] == 1 and abs(E["frames"][-1][0]) == 0 and E["alpha"][-1] == 1
        entry["entrance"] = {"pivot": E["pivot"], "theta": [r5(p[0]) for p in E["frames"]], "rho": [r5(p[1]) for p in E["frames"]], "alpha": [r5(v) for v in E["alpha"]]}
        layers_out.append(entry)
        print(f"{n}: {nv} vertices, {len(L['indices']) // 3} triangles, {K} idle keys, largest interpolation error {err:.4f} ship px, flare peak {np.degrees(np.abs(d[..., 0]).max()):.2f} deg")
    (OUT / "logo-motion.bin").write_bytes(np.concatenate(blob).tobytes())

    # ---- the glint slices: white + alpha at 1x, and the check against the source sweep ------------
    glint_out = {}
    for colour, g in lay["glint"].items():
        slices = []
        tint = None
        full = np.zeros((len(g["slices"]), FRAME[1] * SRC_SCALE, FRAME[0] * SRC_SCALE), np.float32)
        ours = np.zeros_like(full)
        for i, sl in enumerate(g["slices"]):
            a = B.load(LAY / sl["texture"])
            assert a.shape[:2] == (sl["size"][1], sl["size"][0])
            lit = a[..., 3] > 8 / 255  # the colour under near zero alpha is not kept exactly by the source PNGs
            rgb = a[lit][:, :3]
            assert np.ptp(rgb, 0).max() < 1.5 / 255, (sl["texture"], "a slice is one flat colour")
            tint = [int(round(v * 255)) for v in np.median(rgb, 0)]
            name = f"glint_{colour}_{i:02d}"
            white = a.copy()
            white[..., :3] = 1.0
            out, box = B.scaled(white, SRC_SCALE, SCALE["glint"], False)
            out[..., :3] = 1.0
            sprites[name] = [r3(sl["pos"][0] + box[0]), r3(sl["pos"][1] + box[1]), r3(box[2]), r3(box[3])]
            items.append((f"logo_{name}", out))
            slices.append({"sprite": name, "s": sl["s"]})
            x, y = int(sl["pos"][0] * SRC_SCALE), int(sl["pos"][1] * SRC_SCALE)
            full[i, y : y + a.shape[0], x : x + a.shape[1]] = a[..., 3]
            up = np.asarray(Image.fromarray(out[..., 3], "F").resize((out.shape[1] * SRC_SCALE, out.shape[0] * SRC_SCALE), Image.BILINEAR))
            ours[i, y : y + up.shape[0], x : x + up.shape[1]] = up
        hw = g["half_width"]
        worst = mean = 0.0
        for c in np.linspace(-hw, 1 + hw, 41):
            wts = np.array([np.cos(np.pi / 2 * (sl["s"] - c) / hw) ** 2 if abs(sl["s"] - c) < hw else 0.0 for sl in g["slices"]], np.float32)
            d = np.abs(np.tensordot(wts, full - ours, 1))
            worst, mean = max(worst, float(d.max())), max(mean, float(d.mean()))
        print(f"glint {colour}: {len(slices)} slices, tint {tint}; shipped at 1x against the 2x source over a full sweep: largest difference {worst * 255:.1f} / 255 at one texel (an edge), largest mean {mean * 255:.3f} / 255")
        glint_out[colour] = {"halfWidth": hw, "tint": tint, "slices": slices}

    # ---- the atlas ----------------------------------------------------------------------------------
    sheet, frames = B.pack(items)
    img = Image.fromarray((sheet * 255 + 0.5).astype(np.uint8), "RGBA")
    atlas = OUT / "logo.webp"
    img.save(atlas, "WEBP", quality=QUALITY, method=6, alpha_quality=100, exact=True)
    meta = {"image": "logo.webp", "format": "RGBA8888", "size": {"w": img.width, "h": img.height}, "scale": "1", "pngHash": hashlib.md5(atlas.read_bytes()).hexdigest()[:8]}
    (OUT / "logo.json").write_text(json.dumps({"frames": frames, "meta": meta}, indent=1) + "\n")

    data = {
        "frame": FRAME,
        "fps": lay["fps"],
        "art": [r3(v) for v in art],
        "motion": {"unit": UNIT, "idleFrames": N_IDLE, "idleStep": IDLE_STEP, "idleKeys": N_IDLE // IDLE_STEP, "flareFrames": N_FLARE, "entranceFrames": N_ENTER},
        "layers": layers_out,
        "sprites": sprites,
        "glint": glint_out,
    }
    (OUT / "logo-data.json").write_text(json.dumps(data, separators=(",", ":")) + "\n")

    # ---- the budget ---------------------------------------------------------------------------------
    files = [static_path, atlas, OUT / "logo.json", OUT / "logo-data.json", OUT / "logo-motion.bin"]
    for p in files:
        print(f"  {p.relative_to(APP / 'static' / 'assets')}: {p.stat().st_size / 1024:.1f} KB")
    desk = sum(p.stat().st_size for p in files[1:])
    mb = img.width * img.height * 4 / 1048576
    used = sum(im.shape[0] * im.shape[1] for _, im in items)
    print(f"atlas {img.width} x {img.height}, {used / img.width / img.height:.0%} filled: {mb:.2f} MB of RGBA8 on the GPU, {mb * 4 / 3:.2f} MB with its mip chain")
    print(f"desktop tier, deferred: {desk / 1024:.0f} KB (atlas + data + motion). Every tier, landing: logo-stacked.webp {static_path.stat().st_size / 1024:.0f} KB")
    print(f"motion: {off} int16 = {off * 2 / 1024:.0f} KB (the source json is {(LAY / 'logo_stacked_layered.json').stat().st_size / 1024:.0f} KB of text)")


if __name__ == "__main__":
    main()
