// Loads the canvas logo's runtime data once: logo-data.json (topology, entrance tracks, sprite rects, the
// glint recipe) and logo-motion.bin (int16: per wing the bind pose, the idle key frames and the flare),
// decoded to Float32Arrays. GENERATED by tools/build_logo_assets.py; every position is in SHIP px of the
// 754 x 420 logo frame. The atlas rides the deferred asset phase (game/assets.ts, game/deferredLoad.ts).

type WingJson = {
	name: string;
	type: 'mesh';
	frame: string;
	nv: number;
	/** the knuckle the flare turns about */
	pivot: [number, number];
	uvs: number[];
	indices: number[];
	bind: { offset: number };
	idle: { offset: number };
	flare: { offset: number; unit: number };
	/** the whole wing turned (theta, clockwise on screen) and scaled (rho) about its own pivot, per frame */
	entrance: { pivot: [number, number]; theta: number[]; rho: number[]; alpha: number[] };
};
type StaticJson = { name: string; type: 'static'; frame: string; entrance: { pivot: [number, number]; scale: number[]; alpha: number[] } };

export type LogoGlintJson = { halfWidth: number; tint: [number, number, number]; slices: { sprite: string; s: number }[] };
export type LogoJson = {
	frame: [number, number];
	fps: number;
	/** the still's art box in the frame, [x, y, w, h]: what the layout rule places (game/logo/layout.ts) */
	art: [number, number, number, number];
	motion: { unit: number; idleFrames: number; idleStep: number; idleKeys: number; flareFrames: number; entranceFrames: number };
	layers: (WingJson | StaticJson)[];
	/** name -> [x, y, w, h] in the frame */
	sprites: Record<string, [number, number, number, number]>;
	glint: { gold: LogoGlintJson; red: LogoGlintJson };
};

export type LogoWing = {
	name: string;
	frame: string;
	nv: number;
	pivotX: number;
	pivotY: number;
	uvs: Float32Array;
	indices: Uint32Array;
	/** nv x 2 */
	bind: Float32Array;
	/** idleKeys x nv x 2, absolute; key k is idle frame k x idleStep, and the last key runs into the first */
	idle: Float32Array;
	/** flareFrames x nv: radians about the pivot, clockwise on screen, added to the idle */
	flare: Float32Array;
	entrance: WingJson['entrance'];
};
export type LogoStatic = { name: string; frame: string; entrance: StaticJson['entrance'] };
export type LogoData = { json: LogoJson; wings: LogoWing[]; statics: LogoStatic[] };

const floats = (bin: Int16Array, offset: number, count: number, unit: number): Float32Array => {
	const out = new Float32Array(count);
	for (let i = 0; i < count; i += 1) out[i] = bin[offset + i] * unit;
	return out;
};

export const decodeLogo = (json: LogoJson, buffer: ArrayBuffer): LogoData => {
	const bin = new Int16Array(buffer);
	const m = json.motion;
	const wings: LogoWing[] = [];
	const statics: LogoStatic[] = [];
	for (const L of json.layers) {
		if (L.type === 'static') {
			statics.push({ name: L.name, frame: L.frame, entrance: L.entrance });
			continue;
		}
		const n = L.nv * 2;
		wings.push({
			name: L.name,
			frame: L.frame,
			nv: L.nv,
			pivotX: L.pivot[0],
			pivotY: L.pivot[1],
			uvs: new Float32Array(L.uvs),
			indices: new Uint32Array(L.indices),
			bind: floats(bin, L.bind.offset, n, m.unit),
			idle: floats(bin, L.idle.offset, m.idleKeys * n, m.unit),
			flare: floats(bin, L.flare.offset, m.flareFrames * L.nv, L.flare.unit),
			entrance: L.entrance,
		});
	}
	return { json, wings, statics };
};

let pending: Promise<LogoData> | null = null;
let loaded: LogoData | null = null;

/** the data if it is already in (the component reads it on mount, so a logo that is ready plays its entrance) */
export const logoDataNow = (): LogoData | null => loaded;

/** resolves once both files are in; a failed fetch clears the cache so the next call retries */
export const loadLogoData = (urls: { json: string; bin: string }): Promise<LogoData> => {
	pending ??= (async () => {
		const [json, buffer] = await Promise.all([
			fetch(urls.json).then((r) => {
				if (!r.ok) throw new Error(`logo-data.json ${r.status}`);
				return r.json() as Promise<LogoJson>;
			}),
			fetch(urls.bin).then((r) => {
				if (!r.ok) throw new Error(`logo-motion.bin ${r.status}`);
				return r.arrayBuffer();
			}),
		]);
		loaded = decodeLogo(json, buffer);
		return loaded;
	})().catch((error) => {
		pending = null;
		throw error;
	});
	return pending;
};
