// AUTO-GENERATED by tools/build_glyph_atlas.py from
// assets/images/branding/bonus-board-alphabet.webp (Corey's gold bonus-board stencil).
// Display-normalized to a cap height of GOLD_CAP_H; `d` = descent below the baseline.
export const GOLD_CAP_H = 205;
export type GoldGlyph = { w: number; h: number; d: number };
export const GOLD_GLYPHS: Record<string, GoldGlyph> = {
	'A': { w: 184.1, h: 205.0, d: 0.9 },
	'B': { w: 137.6, h: 204.1, d: 0.0 },
	'C': { w: 141.4, h: 205.0, d: 0.0 },
	'D': { w: 143.3, h: 204.1, d: 0.0 },
	'E': { w: 124.3, h: 205.0, d: 0.0 },
	'F': { w: 129.1, h: 204.1, d: 0.0 },
	'G': { w: 143.3, h: 204.1, d: 0.0 },
	'H': { w: 149.0, h: 205.0, d: 0.0 },
	'I': { w: 71.2, h: 204.1, d: 0.0 },
	'J': { w: 133.5, h: 206.0, d: 1.0 },
	'K': { w: 148.7, h: 206.0, d: 1.0 },
	'L': { w: 124.9, h: 205.0, d: 0.0 },
	'M': { w: 175.4, h: 205.0, d: 0.0 },
	'N': { w: 148.7, h: 204.0, d: 0.0 },
	'O': { w: 139.2, h: 205.0, d: 0.0 },
	'P': { w: 142.1, h: 204.0, d: 0.0 },
	'Q': { w: 150.7, h: 218.3, d: 13.3 },
	'R': { w: 156.4, h: 205.0, d: 0.0 },
	'S': { w: 141.3, h: 204.1, d: 0.0 },
	'T': { w: 143.2, h: 204.1, d: 0.0 },
	'U': { w: 147.0, h: 204.1, d: 0.0 },
	'V': { w: 155.4, h: 204.1, d: 0.0 },
	'W': { w: 219.0, h: 204.1, d: 0.0 },
	'X': { w: 175.0, h: 205.9, d: 0.9 },
	'Y': { w: 161.9, h: 205.0, d: 0.9 },
	'Z': { w: 148.8, h: 204.1, d: 0.0 },
	'box1': { w: 220.8, h: 204.2, d: 0.0 },
	'box2': { w: 231.0, h: 205.0, d: 0.0 },
	'box3': { w: 223.9, h: 204.2, d: 0.0 },
};
