// AUTO-GENERATED by tools/build_stencil_atlas.py --font BarlowCondensed-Bold.ttf (plain white glyphs).
// Every number is in EMS (multiply by the font size): `adv` the advance, x / y / w / h the ink
// box from the pen origin on the baseline (y down, so y is negative above it), KERN the GPOS
// pair adjustments, MIDDLE how far above the baseline canvas's textBaseline 'middle' sits.
export const PLATE_GLYPH_PREFIX = 'plate_';
export const PLATE_GLYPH_EM_PX = 160;
export const PLATE_GLYPH_MIDDLE = 0.4;
export type PlateGlyph = { key: string; adv: number; x: number; y: number; w: number; h: number };
export const PLATE_GLYPHS: Record<string, PlateGlyph> = {
	'0': { key: '0', adv: 0.453, x: 0.025, y: -0.7125, w: 0.4, h: 0.7188 },
	'1': { key: '1', adv: 0.284, x: 0.0063, y: -0.7063, w: 0.2437, h: 0.7063 },
	'2': { key: '2', adv: 0.438, x: 0.0187, y: -0.7125, w: 0.4062, h: 0.7125 },
	'3': { key: '3', adv: 0.436, x: 0.0187, y: -0.7063, w: 0.3875, h: 0.7125 },
	'4': { key: '4', adv: 0.484, x: 0.0125, y: -0.7063, w: 0.4625, h: 0.7063 },
	'5': { key: '5', adv: 0.439, x: 0.025, y: -0.7063, w: 0.3937, h: 0.7125 },
	'6': { key: '6', adv: 0.44, x: 0.025, y: -0.7125, w: 0.3937, h: 0.7188 },
	'7': { key: '7', adv: 0.407, x: 0.0125, y: -0.7063, w: 0.3875, h: 0.7063 },
	'8': { key: '8', adv: 0.44, x: 0.025, y: -0.7125, w: 0.3875, h: 0.7188 },
	'9': { key: '9', adv: 0.435, x: 0.0125, y: -0.7125, w: 0.3937, h: 0.7188 },
	'x': { key: 'x', adv: 0.439, x: 0.0125, y: -0.5188, w: 0.4125, h: 0.5188 },
	'×': { key: 'multx', adv: 0.399, x: 0.025, y: -0.4875, w: 0.35, h: 0.35 },
};
export const PLATE_KERN: Record<string, number> = {
	'11': -0.008,
	'12': 0.004,
	'21': -0.014,
	'31': -0.016,
	'41': -0.054,
	'47': -0.056,
	'51': -0.008,
	'61': -0.011,
	'71': -0.003,
	'81': -0.014,
	'91': -0.014,
};
