// GENERATED by tools/build_scene_assets.py from the scene deliverables' chain_layers.json (landscape and phone
// sideways) and portrait_layers.json (portrait): do not edit by hand, rerun the tool when the scene renders change.
// Every number is in px of that scene's FRAME (top-left origin).
// SCENE_SPEC  points: per side the knocker's mouth pivot, where the hanging chain and the swag hook on the ring,
//   the hanging chain's free end, the swag's lowest visible point (swagEnd) and its PIN, where it goes behind the
//   bowl rim (read from the sprite). tiers: the texture sizes and each sprite's box (its atlas frame
//   scene_<piece>_<side>_<set> covers exactly this box).
// SCENE_SPEC_PORTRAIT  no moving pieces. painting / fill: the rows of the frame the painting takes and the rows of
//   the soft mist fill under it, down to where the 3D terrace covers the frame (the board is meant to hide the fill).
// components/Background.svelte and game/scene.ts draw from both.
export const SCENE_SPEC = {
	"source": "knocker_r4",
	"frame": [
		2560,
		1440
	],
	"order": [
		"swag",
		"ring",
		"hang"
	],
	"points": {
		"L": {
			"pivot": [
				302.7,
				330.1
			],
			"hangHook": [
				302.7,
				414.5
			],
			"hangEnd": [
				298.0,
				874.0
			],
			"swagHook": [
				315.3,
				413.2
			],
			"swagEnd": [
				440.0,
				858.0
			],
			"swagPin": [
				388.0,
				716.0
			]
		},
		"R": {
			"pivot": [
				2257.3,
				330.1
			],
			"hangHook": [
				2257.3,
				414.5
			],
			"hangEnd": [
				2252.0,
				764.0
			],
			"swagHook": [
				2244.7,
				413.3
			],
			"swagEnd": [
				2102.0,
				841.0
			],
			"swagPin": [
				2164.0,
				716.0
			]
		}
	},
	"tiers": {
		"full": {
			"size": [
				2560,
				1440
			],
			"fire": [
				1280,
				720
			],
			"boxes": {
				"ring_L": [
					264.0,
					319.0,
					340.0,
					426.0
				],
				"hang_L": [
					277.0,
					393.0,
					329.0,
					879.0
				],
				"swag_L": [
					291.0,
					392.0,
					469.0,
					863.0
				],
				"ring_R": [
					2220.0,
					318.0,
					2296.0,
					426.0
				],
				"hang_R": [
					2232.0,
					393.0,
					2283.0,
					769.0
				],
				"swag_R": [
					2091.0,
					391.0,
					2267.0,
					846.0
				]
			}
		},
		"phone": {
			"size": [
				1600,
				900
			],
			"fire": [
				800,
				450
			],
			"boxes": {
				"ring_L": [
					262.4,
					318.4,
					340.8,
					427.2
				],
				"hang_L": [
					275.2,
					392.0,
					329.6,
					880.0
				],
				"swag_L": [
					289.6,
					390.4,
					470.4,
					864.0
				],
				"ring_R": [
					2219.2,
					316.8,
					2297.6,
					427.2
				],
				"hang_R": [
					2230.4,
					392.0,
					2284.8,
					769.6
				],
				"swag_R": [
					2089.6,
					390.4,
					2268.8,
					848.0
				]
			}
		}
	}
} as const;

export const SCENE_SPEC_PORTRAIT = {
	"source": "portrait_r2",
	"frame": [
		1440,
		2560
	],
	"painting": [
		340,
		1231
	],
	"fill": [
		1231,
		1876
	],
	"tiers": {
		"full": {
			"size": [
				1440,
				2560
			],
			"fire": [
				720,
				1280
			]
		},
		"phone": {
			"size": [
				900,
				1600
			],
			"fire": [
				450,
				800
			]
		}
	}
} as const;
