// The runtime data of the animated win plaque (static/assets/ui/stinger/stinger.json + stinger-motion.bin),
// GENERATED by tools/build_stinger_assets.py from the approved sources. Every position and size is in SHIP
// pixels of the 946 x 532 plaque frame; times are seconds unless a name says Ms.

export const STINGER_TIERS = ['big', 'super', 'mega', 'epic', 'max'] as const;
export type StingerTier = (typeof STINGER_TIERS)[number];
export type StingerScreen = 'win' | 'intro' | 'wrap';
export type StingerMode = 'bonus' | 'super' | 'epic';

type Track = { offset: number; unit: number };
type DeltaTrack = { offset: number; unit: [number, number] };

export type MeshLayerJson = {
	name: string;
	type: 'mesh';
	frame: string;
	nv: number;
	/** a back sheet: draws the named layer's geometry with its own texture */
	share?: string;
	add?: 'linear' | 'polar';
	pivot?: [number, number];
	uvs?: number[];
	indices?: number[];
	bind?: number[];
	idle?: Track;
	tier?: DeltaTrack;
	land?: DeltaTrack;
	/** tier_gain: the tier flare's scale per idle start frame (absent = 1 everywhere) */
	gain?: number[];
};
export type StaticLayerJson = { name: string; type: 'static'; frame: string };
export type LayerJson = MeshLayerJson | StaticLayerJson;

type RGB = [number, number, number];
export type EmberTableJson = { rows: number[][]; points: (number[] | 0)[] };

export type StingerJson = {
	frame: [number, number];
	/** the bind pose art's box [x0, y0, x1, y1] */
	art: [number, number, number, number];
	fps: number;
	tiers: string[];
	motion: { idleFrames: number; tierFrames: number; landFrames: number; landIdleStart: number; layers: LayerJson[] };
	/** name -> [x, y, w, h]: frame coordinates for placed sprites, relative to the anchor for anchored ones */
	sprites: Record<string, [number, number, number, number]>;
	vein: { sprites: string[]; glow: string; slab: string; slabAlpha: number; tiers: { base: number; peak: number; period: number; tint: RGB; glow: number }[] };
	glint: {
		tint: RGB;
		starTint: RGB;
		slices: { sprite: string; s: number }[];
		halfWidth: number;
		idleDuration: number;
		landingDuration: number;
		landingPeak: number;
		sites: { x: number; y: number; s: number; scale: number }[];
		starLife: number;
		landingPick: number[];
		landingExtraDelay: number;
		tiers: { interval: number; peak: number; stars: number }[];
	};
	barb: {
		sides: Record<'L' | 'R', { halo: string; highlight: string; phase: number; idle: number[]; tier: number[]; land: number[]; landVisibility: number[] }>;
		tiers: { base: number; peak: number; period: number; tint: RGB; halo: number }[];
	};
	eyes: {
		eyes: Record<string, { centre: [number, number]; delay: number; size: number; streakRot: number; slant: number; lids: Record<string, string>; glows: Record<string, string> }>;
		blink: { sequence60: number[]; timing: { close: number; hold: number; open: number } };
		flare: { duration: number; attack: number; bloom: string; streak: string; tiers: { gain: number; size: number }[] };
	};
	embers: {
		sprites: string[];
		regions: { name: string; panel: boolean; rect: [number, number, number, number]; killY: number }[];
		exclusions: [number, number, number, number][];
		textZone: { rect: [number, number, number, number]; factor: number };
		tiers: { slots: number; speed: number; alpha: number; twinkle: number; spark: number; streak: number; hot: number; cool: RGB; warm: RGB }[];
		loop: EmberTableJson;
		bursts: EmberTableJson[];
	};
	text: {
		em: number;
		cap: number;
		/** [adv] for a space, else [adv, ox, oy, w, h, frame] in em units of `em` */
		glyphs: Record<string, [number] | [number, number, number, number, number, string]>;
		kern: Record<string, number>;
		titles: Record<string, { frame: string; text: string; w: number; h: number; baseline: number; cap: number; glow?: { tint: string; alpha: number; dx: number; dy: number; w: number; h: number } }>;
		copy: { intro: Record<StingerMode, string[]>; wrap: { title: string; line: string } };
		layout: {
			ship_width: number;
			panel: [number, number, number, number];
			slab_dark: number;
			scene_dim: number;
			intro: { title_cap: number; title_cy: number; text_px: number; rows_cy: number[]; max_width: number };
			win: { title_cap: number; title_cy: number; amount_px: number; amount_cy: number; max_width: number };
			wrap: { title_cap: number; title_cy: number; amount_px: number; amount_cy: number; line_px: number; line_cy: number; max_width: number };
		};
	};
};

/** one deforming layer, tracks decoded to floats once at load */
export type MotionLayer = {
	name: string;
	nv: number;
	polar: boolean;
	pivotX: number;
	pivotY: number;
	uvs: Float32Array;
	indices: Uint32Array;
	/** idleFrames x nv x 2, absolute ship px */
	idle: Float32Array;
	/** tierFrames x nv x 2 / landFrames x nv x 2: (dx, dy) or (theta, rho - 1) */
	tier: Float32Array;
	land: Float32Array;
	/** per idle start frame, or null (1 everywhere) */
	gain: Float32Array | null;
};

export type StingerData = {
	json: StingerJson;
	/** the six movers, in the order of the json's layer list (the back sheets share one of these) */
	movers: MotionLayer[];
};
